<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Unidad_model');
        $this->load->model('Institucion_model');
        $this->load->model('Estado_model');
        $this->load->model('Articulo_model');
        $this->load->model('Programa_model');
        $this->load->model('Proveedor_model');
        $this->load->model('Pedido_model');

    }

    function index()
    {   
        $data['gestion_id'] = 1;        
        $data['gestion_nombre'] = "2019";
        
        $data['unidad'] = $this->Unidad_model->get_unidad_count();        
        $data['programa'] = $this->Programa_model->get_programa_count();        
        $data['institucion'] = $this->Institucion_model->get_all_institucion();        
        $data['articulo'] = $this->Articulo_model->get_articulo_count();        
        $data['proveedor'] = $this->Proveedor_model->get_proveedor_count();        
        $data['estado'] = $this->Estado_model->get_all_estado();        
//        $data['pedido'] = $this->Pedido_model->get_pedido_count();        
        $data['pedido'] = $this->Pedido_model->get_all_pedido();        
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
