<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_pedido extends CI_Controller{
    
    private $session_data = "";
    private $parametros = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detalle_pedido_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
	        
	$this->load->model('Parametros_model');
	$this->parametros = $this->Parametros_model->get_parametros();
	
	    
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        
	$data["parametros"] = $this->parametros;
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
        $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of detalle_pedido
     */
    function index()
    {
	$data["parametros"] = $this->parametros;
        $this->Detalle_pedido_model->bitacora("ACCESO A MODULO","INDEX DETALLE PEDIDO");
        
        if($this->acceso(10)){
            $data['detalle_pedido'] = $this->Detalle_pedido_model->get_all_detalle_pedido();

            $data['_view'] = 'detalle_pedido/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new detalle_pedido
     */
    function add()
    {
	$data["parametros"] = $this->parametros;
        $this->Detalle_pedido_model->bitacora("ACCESO A MODULO","ADD DETALLE PEDIDO");
        if($this->acceso(10)){
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                                    'pedido_id' => $this->input->post('pedido_id'),
                                    'programa_id' => $this->input->post('programa_id'),
                                    'unidad_id' => $this->input->post('unidad_id'),
                );

                $detalle_pedido_id = $this->Detalle_pedido_model->add_detalle_pedido($params);
                redirect('detalle_pedido/index');
            }
            else
            {
                            $this->load->model('Pedido_model');
                            $data['all_pedido'] = $this->Pedido_model->get_all_pedido();

                            $this->load->model('Programa_model');
                            $data['all_programa'] = $this->Programa_model->get_all_programa();

                            $this->load->model('Unidad_model');
                            $data['all_unidad'] = $this->Unidad_model->get_all_unidad();

                $data['_view'] = 'detalle_pedido/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a detalle_pedido
     */
    function edit($detalleped_id)
    {
	$data["parametros"] = $this->parametros;
        $this->Detalle_pedido_model->bitacora("ACCESO A MODULO","EDIT DETALLE PEDIDO");
        if($this->acceso(10)){
            // check if the detalle_pedido exists before trying to edit it
            $data['detalle_pedido'] = $this->Detalle_pedido_model->get_detalle_pedido($detalleped_id);

            if(isset($data['detalle_pedido']['detalleped_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {   
                    $params = array(
                        'pedido_id' => $this->input->post('pedido_id'),
                        'programa_id' => $this->input->post('programa_id'),
                        'unidad_id' => $this->input->post('unidad_id'),
                    );

                    $this->Detalle_pedido_model->update_detalle_pedido($detalleped_id,$params);            
                    redirect('detalle_pedido/index');
                }
                else
                {
                    $this->load->model('Pedido_model');
                    $data['all_pedido'] = $this->Pedido_model->get_all_pedido();

                    $this->load->model('Programa_model');
                    $data['all_programa'] = $this->Programa_model->get_all_programa();

                    $this->load->model('Unidad_model');
                    $data['all_unidad'] = $this->Unidad_model->get_all_unidad();

                    $data['_view'] = 'detalle_pedido/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The detalle_pedido you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting detalle_pedido
     */
    function remove($detalleped_id)
    {
	
        $this->Detalle_pedido_model->bitacora("ACCESO A MODULO","REMOVE DETALLE PEDIDO");
        if($this->acceso(10)){
            $detalle_pedido = $this->Detalle_pedido_model->get_detalle_pedido($detalleped_id);

            // check if the detalle_pedido exists before trying to delete it
            if(isset($detalle_pedido['detalleped_id']))
            {
                $this->Detalle_pedido_model->delete_detalle_pedido($detalleped_id);
                redirect('detalle_pedido/index');
            }
            else
                show_error('The detalle_pedido you are trying to delete does not exist.');
        }
    }
    
}