<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Institucion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Institucion_model');
    } 

    /*
     * Listing of institucion
     */
    function index()
    {
        $data['institucion'] = $this->Institucion_model->get_all_institucion();
        
        $data['_view'] = 'institucion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new institucion
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'institucion_nombre' => $this->input->post('institucion_nombre'),
				'institucion_sucursal' => $this->input->post('institucion_sucursal'),
				'institucion_direccion' => $this->input->post('institucion_direccion'),
				'institucion_ubicacion' => $this->input->post('institucion_ubicacion'),
				'institucion_telef' => $this->input->post('institucion_telef'),
				'institucion_nit' => $this->input->post('institucion_nit'),
				'institucion_autorizacion' => $this->input->post('institucion_autorizacion'),
				'institucion_eslogan' => $this->input->post('institucion_eslogan'),
            );
            
            $institucion_id = $this->Institucion_model->add_institucion($params);
            redirect('institucion/index');
        }
        else
        {            
            $data['_view'] = 'institucion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a institucion
     */
    function edit($institucion_id)
    {   
        // check if the institucion exists before trying to edit it
        $data['institucion'] = $this->Institucion_model->get_institucion($institucion_id);
        
        if(isset($data['institucion']['institucion_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'institucion_nombre' => $this->input->post('institucion_nombre'),
					'institucion_sucursal' => $this->input->post('institucion_sucursal'),
					'institucion_direccion' => $this->input->post('institucion_direccion'),
					'institucion_ubicacion' => $this->input->post('institucion_ubicacion'),
					'institucion_telef' => $this->input->post('institucion_telef'),
					'institucion_nit' => $this->input->post('institucion_nit'),
					'institucion_autorizacion' => $this->input->post('institucion_autorizacion'),
					'institucion_eslogan' => $this->input->post('institucion_eslogan'),
                );

                $this->Institucion_model->update_institucion($institucion_id,$params);            
                redirect('institucion/index');
            }
            else
            {
                $data['_view'] = 'institucion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The institucion you are trying to edit does not exist.');
    }
}
