<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Parametros extends CI_Controller{
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Parametros_model');
        
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    
    private function acceso($id_rol){
        
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    } 
    
    /*
     * Listing of parametros
     */
    function index()
    {
        //if($this->acceso(125)) {
        
            $data['all_parametros'] = $this->Parametros_model->get_allparametros();

            $data['page_title'] = "Parametros";
            $data['_view'] = 'parametros/index';
            $this->load->view('layouts/main',$data);
        //}
    }

    /*
     * Adding a new parametro
     */
    function add()
    {
        //if($this->acceso(125)) {
        if(isset($_POST) && count($_POST) > 0)     
        {
            $params = array(
                'parametro_decimaleskardex' => $this->input->post('parametro_decimaleskardex'),
                'parametro_decimalesoperaciones' => $this->input->post('parametro_decimalesoperaciones'),
            );
            
            $parametro_id = $this->Parametros_model->add_parametro($params);
            redirect('parametros/index');
        }
        else
        {
            $data['page_title'] = "Parametro";
            $data['_view'] = 'parametros/add';
            $this->load->view('layouts/main',$data);
        }
    //} 
    } 

    /*
     * Editing a parametro
     */
    function edit($parametro_id)
    {
        //if($this->acceso(125)) {
        // check if the parametro exists before trying to edit it
        $data['parametro'] = $this->Parametros_model->get_parametro($parametro_id);
        
        if(isset($data['parametro']['parametro_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {
                $params = array(
                    'parametro_decimaleskardex' => $this->input->post('parametro_decimaleskardex'),
                    'parametro_decimalesoperaciones' => $this->input->post('parametro_decimalesoperaciones'),
                );
                $this->Parametros_model->update_parametro($parametro_id,$params);            
                redirect('parametros/index');
            }
            else
            {
                $data['page_title'] = "Parametro";
                $data['_view'] = 'parametros/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The parametro you are trying to edit does not exist.');
    //} 
}
    /*
     * Deleting parametro
     */
    function remove($parametro_id)
    {
        $data['sistema'] = $this->sistema;
        $parametro = $this->Parametro_model->get_parametro($parametro_id);

        // check if the parametro exists before trying to delete it
        if(isset($parametro['parametro_id']))
        {
            $this->Parametro_model->delete_parametro($parametro_id);
            redirect('parametro/index');
        }
        else
            show_error('The parametro you are trying to delete does not exist.');
    }
    
    /* cambia el tipo de emision dela factura */
    function cambiar_tipoemision(){
        
        $data['sistema'] = $this->sistema;
        
        if($this->input->is_ajax_request()){
            
            $parametro_id = $this->input->post('parametro_id');
            $parametro_tipoemision = $this->input->post('parametro_tipoemision');
            $evento_id = $this->input->post('select_eventos');
            $evento_nombre = $this->input->post('select_texto');
            
             $params = array(
                    'parametro_tipoemision' => $parametro_tipoemision,
                );
                $this->Parametro_model->update_parametro($parametro_id,$params);
            
                
           
                
                $usuario_id = $this->session_data['usuario_id'];
                $puntoventa = $this->Usuario_model->get_punto_venta_usuario($usuario_id);
                
                $puntoventa_codigo = $puntoventa['puntoventa_codigo'];
                
                $puntoventa = $this->PuntoVenta_model->get_puntoventa($puntoventa_codigo);
               
                
                
                $sql = "select * from cufd where cufd_codigo = (select cufd_codigo FROM punto_venta where puntoventa_codigo = ".$puntoventa['puntoventa_codigo'].")";
                $resultado = $this->Venta_model->consultar($sql);
                $cufds = $resultado[0];
                
//                $this->load->model('PuntoVenta_model');
//                $punto_venta = $this->PuntoVenta_model->get_puntoventa($puntoventa['puntoventa_codigo']);
//                $dosificacion_id = 1;
//                $dosificacion = $this->Dosificacion_model->get_dosificacion(1);
                
                
            if ($parametro_tipoemision == 1){ //Si regresa a en linea

                    //PASO 1: Actualizamos el registro del evento vigente                
                    //Actualizamos la fecha de cierre del evento vigente
                    
                    $fecha_fin_evento = (new DateTime())->format('Y-m-d\TH:i:s.v');
                
                    $sql = "update registro_eventos set registroeventos_fin = '".$fecha_fin_evento."'
                            where estado_id = 1 and registroeventos_puntodeventa = ".$puntoventa_codigo." and registroeventos_fin is NULL";
                    //echo $sql;
                    $this->Venta_model->ejecutar($sql);
                
                    sleep(30);
                     
                    
                    //PASO 2: Generamos un nuevo CUFD
                        $dosificacion_id = 1;

                        $dosificacion = $this->Dosificacion_model->get_dosificacion($dosificacion_id);
                        $cuis_puntoventa = $this->PuntoVenta_model->get_cuis_puntoventa($puntoventa_codigo);
                        $cuis_puntoventa = $cuis_puntoventa['cuis_codigo'];
                        
                        //$wsdl = "https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionCodigos?wsdl";
                        $wsdl = $dosificacion['dosificacion_obtencioncodigos']; //obtenemos y asignamos el apiKey con el nombre de TokenApi, ejm:
                        $token = $dosificacion['dosificacion_tokendelegado'];

                        $opts = array(
                              'http' => array(
                                   'header' => "apiKey: TokenApi $token",
                              )
                        );


                        $context = stream_context_create($opts);

                        $cliente = new \SoapClient($wsdl, [
                              'stream_context' => $context,
                              'cache_wsdl' => WSDL_CACHE_NONE,
                              'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | SOAP_COMPRESSION_DEFLATE,

                              // other options
                        ]);

                /* ---------------------F I N  segun EJEMPLO ---------------------- */
                /* ordenado segun SoapUI */

//                echo
//                    "codigoAmbiente: ".$dosificacion['dosificacion_ambiente']."<br>".
//                    "codigoModalidad: ".$dosificacion['dosificacion_modalidad']."<br>".
//                    "codigoPuntoVenta: ".$puntoventa_codigo."<br>".
//                    "codigoSistema: ".$dosificacion['dosificacion_codsistema']."<br>".
//                    "codigoSucursal: ".$dosificacion['dosificacion_codsucursal']."<br>".
//                    "cuis: ".$cuis_puntoventa."<br>".
//                    "nit: ".$dosificacion['dosificacion_nitemisor']."<br><br>";

                        $parametros = ["SolicitudCufd" => [
                            "codigoAmbiente"=>  $dosificacion['dosificacion_ambiente'],
                            "codigoModalidad"=> $dosificacion['dosificacion_modalidad'],
                            "codigoPuntoVenta"=>   $puntoventa_codigo, //$dosificacion['dosificacion_puntoventa'],
                            "codigoSistema"=>   $dosificacion['dosificacion_codsistema'],
                            "codigoSucursal"=>  $dosificacion['dosificacion_codsucursal'],
                            "cuis"=>            $cuis_puntoventa, //$dosificacion['dosificacion_cuis'],
                            "nit"=>             $dosificacion['dosificacion_nitemisor']
                                ]];
                        
                    //Generando CUFD Nuevo
                    $resultado = $cliente->cufd($parametros);

                    
                    if($resultado->RespuestaCufd->transaccion){ //Si genero el CUFD correctamente lo registra en la tabla CUFD y actualiza la tabla PUNTO_VENTA

                            $cufd_codigo = "'".$resultado->RespuestaCufd->codigo."'";
                            $cufd_codigocontrol = "'".$resultado->RespuestaCufd->codigoControl."'";
                            $cufd_direccion = "'".$resultado->RespuestaCufd->direccion."'";
                            $cufd_fechavigencia = "'".$resultado->RespuestaCufd->fechaVigencia."'";
                            //$cufd_transaccion = true;
                            $cufd_puntodeventa =  $puntoventa_codigo;

                            $dosificacion = $this->Dosificacion_model->get_dosificacion(1);
                            // $cufd_puntodeventa = $dosificacion["dosificacion_puntoventa"];

                            $sql = "insert into cufd(cufd_codigo,cufd_codigocontrol,cufd_direccion,cufd_fechavigencia,cufd_transaccion, cufd_puntodeventa, cufd_fecharegistro) value(".
                                        $cufd_codigo.",".$cufd_codigocontrol.",".$cufd_direccion.",".$cufd_fechavigencia.",'true',".$cufd_puntodeventa.", now())";
                            $this->Dosificacion_model->ejecutar($sql);

                            // $sql = "update dosificacion set dosificacion_cufd = ".$cufd_codigo;
                            // $this->Dosificacion_model->ejecutar($sql);
                            $sql = "UPDATE punto_venta 
                                    set cufd_codigo = $cufd_codigo
                                    where puntoventa_codigo = $cufd_puntodeventa";
                            $this->Dosificacion_model->ejecutar($sql);
                        
                    }
            

                

                    //PASO 3: Registramos el evento en el SIN

                    
                    $wsdl = $dosificacion['dosificacion_operaciones'];
                    
                    $token = $dosificacion['dosificacion_tokendelegado'];
                    
                    $opts = array(
                          'http' => array(
                               'header' => "apiKey: TokenApi $token",
                          )
                    );
                    $context = stream_context_create($opts);

                    $cliente = new \SoapClient($wsdl, [
                          'stream_context' => $context,
                          'cache_wsdl' => WSDL_CACHE_NONE,
                          'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | SOAP_COMPRESSION_DEFLATE,

                          // other options
                    ]);

                    
                    $sql = "select * from registro_eventos where estado_id = 1 and registroeventos_puntodeventa = ".$puntoventa_codigo;
                    //echo $sql;
                    $eventos = $this->Venta_model->consultar($sql);
                    $evento = $eventos[0];
                    
//                    $usuario_id = $this->session_data['usuario_id'];
//                    $puntoventa = $this->Usuario_model->get_punto_venta_usuario($usuario_id);
//                    $this->load->model('PuntoVenta_model');
//                    $punto_venta = $this->PuntoVenta_model->get_puntoventa($puntoventa['puntoventa_codigo']);
//                    $puntodeventa = $punto_venta['puntoventa_codigo']; //$dosificacion['dosificacion_puntoventa'];
//                    

                    $fecha_i = $evento['registroeventos_inicio'];
                    /*
                    $fecha_inicio = $evento['registroeventos_inicio'];
                    $fecha_i = date("Y-m-d\TH:i:s.v", strtotime($fecha_inicio));
                    $fecha_i = $fecha_i.".".rand(10,60);
                    */
                    //$fecha_fin = new DateTime(date('Y-m-d\TH:i:s'));
//                    $fecha_fin = date('Y-m-d\TH:i:s'); //new DateTime(date('Y-m-d\TH:i:s'));
                    
                    $fecha_f = $evento['registroeventos_fin'];
                    /*$fecha_fin = $evento['registroeventos_fin'];
                    $fecha_f = date("Y-m-d\TH:i:s.v", strtotime($fecha_fin));
                    $fecha_f = $fecha_f.".".rand(10,60);
                    */
//                    echo "<br>".$evento['registroeventos_cufd'];
//                    echo "<br>".$fecha_i." *** ".$fecha_f;
                    
/*                    echo
                        "<br>codigoAmbiente: ".$dosificacion['dosificacion_ambiente'].
                        "<br>codigoMotivoEvento: ".$evento['registroeventos_codigoevento']. //$dosificacion['dosificacion_codsistema'],
                        "<br>codigoPuntoVenta: ".$puntoventa_codigo. //$dosificacion['dosificacion_puntoventa'],
                        "<br>codigoSistema: ".$dosificacion['dosificacion_codsistema'].
                        "<br>codigoSucursal: ".$dosificacion['dosificacion_codsucursal'].
                        "<br>cufd: ".$puntoventa['cufd_codigo']. //$dosificacion['dosificacion_cufd'],
                        "<br>cufdEvento: ".$evento['registroeventos_cufd']. //$dosificacion['dosificacion_cuis'],
                        "<br>cuis: ".$puntoventa['cuis_codigo']. //$dosificacion['dosificacion_cuis'],
                        "<br>descripcion: ".$evento['registroeventos_detalle']. //$dosificacion['dosificacion_cuis'],
                        "<br>fechaHoraFinEvento: ".$fecha_f. //$dosificacion['dosificacion_cuis'],
                        "<br>fechaHoraInicioEvento: ".$fecha_i. //$dosificacion['dosificacion_cuis'],
                        "<br>nit: ".$dosificacion['dosificacion_nitemisor'];*/
                    

                    // Actualizamos punto de venta porque registramos un nuevo CUFD

                    $puntoventa = $this->PuntoVenta_model->get_puntoventa($puntoventa_codigo);

                    $parametros = ["SolicitudEventoSignificativo" => [
                        "codigoAmbiente"    => $dosificacion['dosificacion_ambiente'],
                        "codigoMotivoEvento"=> $evento['registroeventos_codigoevento'], //$dosificacion['dosificacion_codsistema'],
                        "codigoPuntoVenta"  => $puntoventa_codigo, //$dosificacion['dosificacion_puntoventa'],
                        "codigoSistema"     => $dosificacion['dosificacion_codsistema'],
                        "codigoSucursal"    => $dosificacion['dosificacion_codsucursal'],
                        "cufd"              => $puntoventa['cufd_codigo'], //$dosificacion['dosificacion_cufd'],
                        "cufdEvento"        => $evento['registroeventos_cufd'], //$dosificacion['dosificacion_cuis'],
                        "cuis"              => $puntoventa['cuis_codigo'], //$dosificacion['dosificacion_cuis'],
                        "descripcion"       => $evento['registroeventos_detalle'], //$dosificacion['dosificacion_cuis'],
                        "fechaHoraFinEvento"=> $fecha_f, //$dosificacion['dosificacion_cuis'],
                        "fechaHoraInicioEvento"=>$fecha_i, //$dosificacion['dosificacion_cuis'],
                        "nit"               => $dosificacion['dosificacion_nitemisor']
                    ]];
                    
                    
                    
                    
                    sleep(1);
                    //Agarramos el registro del evento significativo
                    //var_dump($parametros);
                    $resultado = $cliente->registroEventoSignificativo($parametros);
                    sleep(1);
                    //var_dump($resultado);
                    $res = $resultado->RespuestaListaEventos->transaccion;
                    $mensaje = "";

//                    var_dump($resultado);
//                    var_dump($res);
                    

                    
                    if($res){
                    
                            $cufdes = $this->Venta_model->consultar("select * from cufd where cufd_codigo = '".$puntoventa['cufd_codigo']."'");
                            $registroeventos_cufd = $cufdes[0]["cufd_codigo"];
                            $registroeventos_codigocontrol = $cufdes[0]["cufd_codigocontrol"];

        //                        var_dump($resultado);
        //                        var_dump($res);


                            //PASO 4: Si todo esta OK, actualizamos el codigo devuelto por el SIN

                            if ($res){
                                
                                $codigo_recepcion = $resultado->RespuestaListaEventos->codigoRecepcionEventoSignificativo;

                                $sql = "update registro_eventos set registroeventos_codigo = '".$codigo_recepcion."'"." where registroeventos_id = ".$evento['registroeventos_id'];
                                $this->Eventos_significativos_model->ejecutar($sql);

                               // $mensaje = "EVENTO REGISTRADO CON ÉXITO, CODIGO RECEPCION: ".$codigo_recepcion.",".$evento['registroeventos_codigoevento'];

                                //PASO 5: Contar los archivos que se deben subir
                                // Solo contabamos las facturas, necesitamos el email del cliente
                                // $sql = "select * from factura where registroeventos_id = ".$evento['registroeventos_id'];
                                $sql = "select f.*, c.cliente_email  from factura f, venta v, cliente c
                                        where                                         
                                        f.registroeventos_id = ".$evento['registroeventos_id']." and 
                                        f.venta_id = v.venta_id and
                                        v.cliente_id = c.cliente_id ";
                                
                                $facturas = $this->Venta_model->consultar($sql);
                                $cantidad_facturas = sizeof($facturas);

                                //PASO 6: Comprimir archivos generados en la contingencia
                                $base_url = explode('/', base_url());  //convierte un cadena en array
                                $directorio = $_SERVER['DOCUMENT_ROOT'].'/'.$base_url[3].'/resources/xml/';


                                $p = new PharData($directorio."contingencia".$codigo_recepcion.".tar");
                                $nombre_archivo = $this->nombre_archivo;
                                
                                foreach ($facturas as $f){

                                    $datos = implode("", file($directorio.$nombre_archivo.$f["factura_id"].".xml")); //convierte un array en cadena y asignamos a datos
                                    $p[$nombre_archivo.$f['factura_id'].".xml"] = $datos;

                                }

                                $p->compress(Phar::GZ);                        

                            //echo "Paso 7";
                                //PASO 7: Enviar los archivos generados en el .tar.gz
                                $dosificacion = $this->Dosificacion_model->get_dosificacion(1);
                                
                                if ($dosificacion['docsec_codigoclasificador']==1)
                                    $wsdl = $dosificacion['dosificacion_factura'];

                                if ($dosificacion['dosificacion_modalidad']==1){ //Electronica en linea
                                    if ($dosificacion['docsec_codigoclasificador']==2 || $dosificacion['docsec_codigoclasificador']==23 || $dosificacion['docsec_codigoclasificador']==39
                                            || $dosificacion['docsec_codigoclasificador']==11 || $dosificacion['docsec_codigoclasificador']==12 || $dosificacion['docsec_codigoclasificador']==8 || $dosificacion['docsec_codigoclasificador']==51)
                                    $wsdl = $dosificacion['dosificacion_glpelectronica'];
                                }
                                if ($dosificacion['dosificacion_modalidad']==2){ // Computarizada en linea
                                    if ($dosificacion['docsec_codigoclasificador']==2 || $dosificacion['docsec_codigoclasificador']==23 || $dosificacion['docsec_codigoclasificador']==39
                                            || $dosificacion['docsec_codigoclasificador']==11 || $dosificacion['docsec_codigoclasificador']==12 || $dosificacion['docsec_codigoclasificador']==8 || $dosificacion['docsec_codigoclasificador']==51)
                                    $wsdl = $dosificacion['dosificacion_facturaglp'];
                                }
                                
                                
                                $token = $dosificacion['dosificacion_tokendelegado'];
                                $opts = array(
                                      'http' => array(
                                           'header' => "apiKey: TokenApi $token",
                                      )
                                );
                                $context = stream_context_create($opts);

                                $cliente = new \SoapClient($wsdl, [
                                      'stream_context' => $context,
                                      'cache_wsdl' => WSDL_CACHE_NONE,
                                      'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | SOAP_COMPRESSION_DEFLATE,

                                      // other options
                                ]);

                                $base_url = explode('/', base_url());
                                //$doc_xml = site_url("resources/xml/$archivoXml.xml");
                                $directorio = $_SERVER['DOCUMENT_ROOT'].'/'.$base_url[3].'/resources/xml/';


                                $nom_archivo =  "contingencia".$codigo_recepcion.".tar.gz";
                                $codigo_evento =  $codigo_recepcion;
                                $cant_fact =  $cantidad_facturas;


        //                        $factura_id = substr($nom_archivo,12, strlen($nom_archivo));
                                $factura_id = 0;

                                $handle = fopen($directorio.$nom_archivo, "rb");
                                $contents = fread($handle, filesize($directorio.$nom_archivo));
                                fclose($handle);

                                $xml_comprimido = hash_file('sha256',$directorio.$nom_archivo);
                                $has_archivo = $xml_comprimido;

                                //$usuario_id = $this->session_data['usuario_id'];
        //                        $puntoventa = $this->Usuario_model->get_punto_venta_usuario($usuario_id);
        //                        $this->load->model('PuntoVenta_model');
        //                        $punto_venta = $this->PuntoVenta_model->get_puntoventa($puntoventa['puntoventa_codigo']);
        //                        
                                $tipo_emision = 2;//1 offline

                                $fecha_hora = (new DateTime())->format('Y-m-d\TH:i:s.v');
                                $parametros = ["SolicitudServicioRecepcionPaquete" => [
                                    "codigoAmbiente" => $dosificacion['dosificacion_ambiente'],
                                    "codigoPuntoVenta"    => $puntoventa['puntoventa_codigo'],
                                    "codigoSistema"        => $dosificacion['dosificacion_codsistema'],
                                    "codigoSucursal"       => $dosificacion['dosificacion_sucursal'],
                                    "nit"              => $dosificacion['dosificacion_nitemisor'],
                                    "codigoDocumentoSector"=> $dosificacion['docsec_codigoclasificador'],
                                    "codigoEmision"  => $tipo_emision,
                                    "codigoModalidad"     => $dosificacion['dosificacion_modalidad'],
                                    "cufd"              => $puntoventa['cufd_codigo'],
                                    "cuis"              => $puntoventa['cuis_codigo'],
                                    "tipoFacturaDocumento" => $dosificacion['tipofac_codigo'],
                                    "archivo" => $contents,
                                    "fechaEnvio"=>$fecha_hora,
                                    "hashArchivo"=>$has_archivo,
                                    "cafc"               => $dosificacion['dosificacion_cafc'],
                                    "cantidadFacturas"     => $cant_fact,
                                    "codigoEvento"         => $codigo_evento,
                                ]];

                                $fecha_hora1 = (new DateTime())->format('Y-m-d H:i:s');
                                //var_dump($parametros);
                                sleep(1);
                                $resultado = $cliente->recepcionPaqueteFactura($parametros);
                                $res = $resultado->RespuestaServicioFacturacion;


                                if($res->codigoDescripcion == "PENDIENTE"){
                                    
                                    $params = array(
                                        'recpaquete_codigodescripcion' => $res->codigoDescripcion,
                                        'recpaquete_codigoestado' => $res->codigoEstado,
                                        'recpaquete_codigorecepcion' => $res->codigoRecepcion,
                                        'recpaquete_transaccion' => $res->transaccion,
                                        'recpaquete_fechahora' => $fecha_hora1,
                                        'codigo_evento' => $codigo_evento,
                                        'factura_id' => $factura_id,
                                    );
                                    
                                }else{
                                    
                                    $cad = $res->mensajesList;
                                            $mensajecadena = "";
                                            foreach ($cad as $c) {
                                                $mensajecadena .= $c.";";
                                            }
                                    $params = array(
                                        'recpaquete_codigodescripcion' => $res->codigoDescripcion,
                                        'recpaquete_codigoestado' => $res->codigoEstado,
                                        //'recpaquete_codigorecepcion' => $res->codigoRecepcion,
                                        'recpaquete_mensajeslist' => $mensajecadena,
                                        'recpaquete_fechahora' => $fecha_hora1,
                                        'codigo_evento' => $codigo_evento,
                                        'factura_id' => $factura_id,
                                    );
                                    
                                } 

                                $recpaquete_id = $this->Emision_paquetes_model->add_recepcionpaquetes($params);

                                //PASO 8: Envio de los archivos
                                $dosificacion = $this->Dosificacion_model->get_dosificacion(1);
                                
                                if ($dosificacion['docsec_codigoclasificador']==1)
                                    $wsdl = $dosificacion['dosificacion_factura'];

                                if ($dosificacion['dosificacion_modalidad']==1){ //Electronica en linea
                                    if ($dosificacion['docsec_codigoclasificador']==23 || $dosificacion['docsec_codigoclasificador']==39 || $dosificacion['docsec_codigoclasificador']==11)
                                    $wsdl = $dosificacion['dosificacion_glpelectronica'];
                                }
                                if ($dosificacion['dosificacion_modalidad']==2){ // Computarizada en linea
                                    if ($dosificacion['docsec_codigoclasificador']==23 || $dosificacion['docsec_codigoclasificador']==39 || $dosificacion['docsec_codigoclasificador']==11)
                                    $wsdl = $dosificacion['dosificacion_facturaglp'];
                                }
                                
                                $token = $dosificacion['dosificacion_tokendelegado'];

                                $opts = array(
                                      'http' => array(
                                           'header' => "apiKey: TokenApi $token",
                                      )
                                );
                                $context = stream_context_create($opts);

                                $cliente = new \SoapClient($wsdl, [
                                      'stream_context' => $context,
                                      'cache_wsdl' => WSDL_CACHE_NONE,
                                      'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | SOAP_COMPRESSION_DEFLATE,

                                      // other options
                                ]);

                                $codigo_recepcion =  $res->codigoRecepcion;
                                $factura_id =  0;
                                //$codigo_recepcion = '2d3b23e5-f882-11ec-8853-632ba520e7ec';
                                /*$handle = fopen($directorio.$nom_archivo, "rb");
                                $contents = fread($handle, filesize($directorio.$nom_archivo));
                                fclose($handle);
                                 * 
                                $xml_comprimido = hash_file('sha256',$directorio.$nom_archivo);
                                 */

                                //$has_archivo = ''; //$xml_comprimido;

        //                        $usuario_id = $this->session_data['usuario_id'];
        //                        $puntoventa = $this->Usuario_model->get_punto_venta_usuario($usuario_id);
        //                        $this->load->model('PuntoVenta_model');
        //                        $punto_venta = $this->PuntoVenta_model->get_puntoventa($puntoventa['puntoventa_codigo']);
                                $tipo_emision = 2; //1 offline
                                //$fecha_hora = (new DateTime())->format('Y-m-d\TH:i:s.v');
                                $parametros = ["SolicitudServicioValidacionRecepcionPaquete" => [
                                    "codigoAmbiente" => $dosificacion['dosificacion_ambiente'],
                                    "codigoPuntoVenta"    => $puntoventa['puntoventa_codigo'], //$dosificacion['dosificacion_puntoventa'],
                                    "codigoSistema"        => $dosificacion['dosificacion_codsistema'],
                                    "codigoSucursal"       => $dosificacion['dosificacion_sucursal'],
                                    "nit"              => $dosificacion['dosificacion_nitemisor'],
                                    "codigoDocumentoSector"=> $dosificacion['docsec_codigoclasificador'],
                                    "codigoEmision"  => $tipo_emision,
                                    "codigoModalidad"     => $dosificacion['dosificacion_modalidad'],
                                    "cufd"              => $puntoventa['cufd_codigo'], //$dosificacion['dosificacion_cufd'],
                                    "cuis"              => $puntoventa['cuis_codigo'], //$dosificacion['dosificacion_cuis'],
                                    "tipoFacturaDocumento" => $dosificacion['tipofac_codigo'],
                                    "codigoRecepcion"         => $codigo_recepcion, //$dosificacion['dosificacion_nitemisor']
                                ]];

                                $fecha_hora1 = (new DateTime())->format('Y-m-d H:i:s');
                                //var_dump($parametros);

                                $resultado = $cliente->validacionRecepcionPaqueteFactura($parametros);
                                $res = $resultado->RespuestaServicioFacturacion;
                                $resultado = $resultado->RespuestaServicioFacturacion->transaccion;
                                sleep(1);
                                
                                //var_dump($res);
                                if($resultado){
   
                                        $recepcion_paquete = $this->Emision_paquetes_model->getcod_recepcionpaquetes($res->codigoRecepcion);

                                        if($res->codigoDescripcion == "VALIDADA"){

                                            $params = array(
                                                'recpaquete_codigodescripcion' => $res->codigoDescripcion,
                                                'recpaquete_codigoestado' => $res->codigoEstado,
                                            );

                                            $sql = "update factura set factura_codigodescripcion ='VALIDADA', factura_enviada = 2  where factura_id='".$factura_id."'";
                                            $this->Venta_model->ejecutar($sql);


                                        }elseif($res->codigoDescripcion == "OBSERVADA"){

                                            $cad = $res->mensajesList;
                                            $mensajecadena = json_encode($cad);

                                            /*foreach ($cad as $c) {
                                                $mensajecadena .= $c.";";
                                            }*/
                                            $params = array(
                                                'recpaquete_codigodescripcion' => $res->codigoDescripcion,
                                                'recpaquete_codigoestado' => $res->codigoEstado,
                                                'recpaquete_mensajeslist' => $mensajecadena,
                                            );

                                        }
                                        
                                        $this->Emision_paquetes_model->update_recepcionpaquetes($recepcion_paquete['recpaquete_id'],$params);

                                        //echo json_encode($res);
                                        //PASO 9: Actualizar datos de envio en las facturas
                                        
                                        $sql = "update factura set 
                                                 factura_codigodescripcion = 'VALIDADA'
                                                ,factura_enviada = 2
                                                ,factura_codigorecepcion= '".$res->codigoRecepcion."'
                                                 where registroeventos_id = ".$evento['registroeventos_id'];
                                        $this->Venta_model->ejecutar($sql);
                                        //Esto debe ocurrir solo en el evento 1
                                        if($evento['registroeventos_codigoevento'] == 1 || $evento['registroeventos_codigoevento'] == 3){
                                            foreach ($facturas as $f){
                                                $venta_id = $f["venta_id"];
                                                $factura_id = $f["factura_id"];
                                                $email = $f["cliente_email"];
                                                if ($f["cliente_email"]!=null){
                                                    $this->enviarcorreo($venta_id, $factura_id, $email);
                                                }
                                            }
                                        }
                                        
                                        //************ actualizar lista de eventos**********************
                                        $sql = "update registro_eventos set estado_id = 2 where registroeventos_puntodeventa = ".$puntoventa['puntoventa_codigo'];
                                        $this->Venta_model->ejecutar($sql);
                                        
                                        //***************************************************************
                                        
                                        echo json_encode($res);
                                        
                            //*************
                            }else{
                                echo json_encode($res);
                            }
                            //*************

                            }else{

//                                $mensajeresultado = $resultado->RespuestaListaEventos->mensajesList;
//                                $mensaje = "OCURRIO UN ERROR, CODIGO: ".$mensajeresultado->codigo.", ".$mensajeresultado->descripcion;
                                echo json_encode($resultado);
                            }

                            //echo json_encode("ok");
                            
                    }else{ //fin if ($res)  al generar el codigoevento
                        echo json_encode($resultado);
                    }
                    
                    
                
            }else{ //Si es fuera de linea
                
                //Verificar si exite un evento
                //$sql = "select * from registro_eventos 
                //        where estado_id = 1 and registroeventos_puntodeventa = ".$puntoventa["puntoventa_codigo"];
                //$result =  $this->Venta_model->consultar($sql);
                
                //if(!sizeof($result)>0){
                if(1>0){
                        // filtramos todos los puntos de venta existentes
                        $sql = "select * from punto_venta";
                        $puntos = $this->Venta_model->consultar($sql);
                        
                        foreach($puntos as $puntoventa){ //Reccorremos todos los puntos de venta existentes
                            
                            //Selecccionamos en ultimo CUFD en uso del punto de venta seleccionado
                            $sql = "select * from cufd where cufd_codigo = (select cufd_codigo FROM punto_venta where puntoventa_codigo = ".$puntoventa['puntoventa_codigo'].")";
                            $resultado = $this->Venta_model->consultar($sql);
                            
                            if(sizeof($resultado)>0){
                                
                                    $cufds = $resultado[0];
                                    
                                //verificamos si ya tenemos un evento de este dia asociado y activo 
                                    
                                $sql = "select * from registro_eventos where date(registroeventos_inicio) = date(now()) and estado_id = 1 and registroeventos_puntodeventa = ".$puntoventa['puntoventa_codigo'];
                                $eventos = $this->Venta_model->consultar($sql);
                                
                                if (sizeof($eventos)<1){ //Si NO existe un evento asociado al dia de hoy para el punto de venta, lo debe generar
                                    
                                    
                                    $registroeventos_codigo = "''";
                                    $registroeventos_codigoevento = $evento_id;
                                    $registroeventos_detalle = "'".$evento_nombre."'";
                                    $registroeventos_fecha = "now()";
                                    $registroeventos_puntodeventa = $cufds["cufd_puntodeventa"];
                                    $registroeventos_inicio = (new DateTime())->format('Y-m-d\TH:i:s.v'); //"now()";
                                    $registroeventos_cufd = "'".$cufds["cufd_codigo"]."'";
                                    $registroeventos_codigocontrol = "'".$cufds["cufd_codigocontrol"]."'";
                                    $estado_id = 1;

                                    //inactivamos los eventos anteriores del mismo punto de venta
                                    $sql = "update registro_eventos set estado_id = 2 where registroeventos_puntodeventa = ".$puntoventa['puntoventa_codigo'];
                                    $this->Venta_model->ejecutar($sql);

                                    //registramos el nuevo evento
                                    $sql = "insert into registro_eventos(registroeventos_codigo, registroeventos_codigoevento, registroeventos_detalle, registroeventos_fecha, registroeventos_puntodeventa, registroeventos_inicio, registroeventos_cufd, registroeventos_codigocontrol, estado_id) value(".
                                            $registroeventos_codigo.",".$registroeventos_codigoevento.",".$registroeventos_detalle.",".$registroeventos_fecha.",".$registroeventos_puntodeventa.",'".$registroeventos_inicio."',".$registroeventos_cufd.",".$registroeventos_codigocontrol.",".$estado_id.")";
                                    $this->Venta_model->ejecutar($sql);
                                    
                                } //fin if (! sizeof($eventos)>0)
                            }

                        } //fin foreach
                        
                        echo json_encode("Evento registrado correctamente..!!");
                    
                }else{
                    echo json_encode("ADVENTENCIA: Ya existe un evento registrado...!");
                }
                
            }
                
        }
    }
    
    /* viene desde ventas cuando es
     * con CAFC prepara y envia el paquete a impuestos para su recepcion y validacion! */
    function enviar_paquete(){
        
        $data['sistema'] = $this->sistema;
        if($this->input->is_ajax_request()){
            
            $codigo_evento = $this->input->post('codigo_evento');
            
            $dosificacion_id = 1;
            $dosificacion = $this->Dosificacion_model->get_dosificacion($dosificacion_id);
            
            $usuario_id = $this->session_data['usuario_id'];
            $elpuntoventa = $this->Usuario_model->get_punto_venta_usuario($usuario_id);

            $puntoventa_codigo = $elpuntoventa['puntoventa_codigo'];

            $puntoventa = $this->PuntoVenta_model->get_puntoventa($puntoventa_codigo);
            
            // los pasos previos (1..5) no son necesarios ya que se genero el evento antes de llamar a esta funcion
            
            //PASO 6: Contar los archivos que se deben subir
            $sql = "select * from registro_eventos where registroeventos_codigo = ".$codigo_evento;
            $eventos = $this->Venta_model->consultar($sql);
            $evento = $eventos[0];

            $sql = "select * from factura where factura_enviada = 0 and registroeventos_id = ".$evento['registroeventos_id'];
            $facturas = $this->Venta_model->consultar($sql);
            $cantidad_facturas = sizeof($facturas);
            //var_dump($cantidad_facturas."<br>");
            //PASO 7: Comprimir archivos generados en la contingencia
            $base_url = explode('/', base_url());  //convierte un cadena en array
            $directorio = $_SERVER['DOCUMENT_ROOT'].'/'.$base_url[3].'/resources/xml/';

            $codigo_recepcion = $codigo_evento;
            if(file_exists($directorio."contingencia".$codigo_recepcion.".tar")){
                unlink($directorio."contingencia".$codigo_recepcion.".tar");
                unlink($directorio."contingencia".$codigo_recepcion.".tar.gz");
            }
            
            $p = new PharData($directorio."contingencia".$codigo_recepcion.".tar");

            $nombre_archivo = $this->nombre_archivo;
            foreach ($facturas as $f){

                $datos = implode("", file($directorio.$nombre_archivo.$f["factura_id"].".xml")); //convierte un array en cadena y asignamos a datos
                $p[$nombre_archivo.$f['factura_id'].".xml"] = $datos;

            }

            $p->compress(Phar::GZ);                        

            //PASO 8: Enviar los archivos generados en el .tar.gz
            //$dosificacion = $this->Dosificacion_model->get_dosificacion(1);
            if ($dosificacion['docsec_codigoclasificador']==1)
                $wsdl = $dosificacion['dosificacion_factura'];

            if ($dosificacion['dosificacion_modalidad']==1){ //Electronica en linea
                if ($dosificacion['docsec_codigoclasificador']==23 || $dosificacion['docsec_codigoclasificador']==39 || $dosificacion['docsec_codigoclasificador']==11)
                $wsdl = $dosificacion['dosificacion_glpelectronica'];
            }
            if ($dosificacion['dosificacion_modalidad']==2){ // Computarizada en linea
                if ($dosificacion['docsec_codigoclasificador']==23 || $dosificacion['docsec_codigoclasificador']==39 || $dosificacion['docsec_codigoclasificador']==11)
                $wsdl = $dosificacion['dosificacion_facturaglp'];
            }

            $token = $dosificacion['dosificacion_tokendelegado'];
            $opts = array(
                  'http' => array(
                       'header' => "apiKey: TokenApi $token",
                  )
            );
            $context = stream_context_create($opts);

            $cliente = new \SoapClient($wsdl, [
                  'stream_context' => $context,
                  'cache_wsdl' => WSDL_CACHE_NONE,
                  'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | SOAP_COMPRESSION_DEFLATE,

                  // other options
            ]);
            
            $nom_archivo =  "contingencia".$codigo_recepcion.".tar.gz";
            //$codigo_evento =  $codigo_recepcion;
            $cant_fact =  $cantidad_facturas;
            
            $handle = fopen($directorio.$nom_archivo, "rb");
            $contents = fread($handle, filesize($directorio.$nom_archivo));
            fclose($handle);

            $xml_comprimido = hash_file('sha256',$directorio.$nom_archivo);
            $has_archivo = $xml_comprimido;
            
            $tipo_emision = 2;//1 online; 2 offline

            $fecha_hora = (new DateTime())->format('Y-m-d\TH:i:s.v');
            $parametros = ["SolicitudServicioRecepcionPaquete" => [
                "codigoAmbiente" => $dosificacion['dosificacion_ambiente'],
                "codigoPuntoVenta"    => $puntoventa['puntoventa_codigo'],
                "codigoSistema"        => $dosificacion['dosificacion_codsistema'],
                "codigoSucursal"       => $dosificacion['dosificacion_sucursal'],
                "nit"              => $dosificacion['dosificacion_nitemisor'],
                "codigoDocumentoSector"=> $dosificacion['docsec_codigoclasificador'],
                "codigoEmision"  => $tipo_emision,
                "codigoModalidad"     => $dosificacion['dosificacion_modalidad'],
                "cufd"              => $puntoventa['cufd_codigo'],
                "cuis"              => $puntoventa['cuis_codigo'],
                "tipoFacturaDocumento" => $dosificacion['tipofac_codigo'],
                "archivo" => $contents,
                "fechaEnvio"=>$fecha_hora,
                "hashArchivo"=>$has_archivo,
                "cafc"               => $dosificacion['dosificacion_cafc'],
                "cantidadFacturas"     => $cant_fact,
                "codigoEvento"         => $codigo_evento,
            ]];

            $fecha_hora1 = (new DateTime())->format('Y-m-d H:i:s');
            //var_dump($parametros);
            $resultado = $cliente->recepcionPaqueteFactura($parametros);
            $res = $resultado->RespuestaServicioFacturacion;
            /* esta solicitud de recepcion se registra en recepcion paquetes! */
            $factura_id = 0; // porque es paquete de facturas.
            if($res->codigoDescripcion == "PENDIENTE"){
                $params = array(
                    'recpaquete_codigodescripcion' => $res->codigoDescripcion,
                    'recpaquete_codigoestado' => $res->codigoEstado,
                    'recpaquete_codigorecepcion' => $res->codigoRecepcion,
                    'recpaquete_transaccion' => $res->transaccion,
                    'recpaquete_fechahora' => $fecha_hora1,
                    'codigo_evento' => $codigo_evento,
                    'factura_id' => $factura_id,
                );
            }else{
                $cad = $res->mensajesList;
                        $mensajecadena = "";
                        foreach ($cad as $c) {
                            $mensajecadena .= $c.";";
                        }
                $params = array(
                    'recpaquete_codigodescripcion' => $res->codigoDescripcion,
                    'recpaquete_codigoestado' => $res->codigoEstado,
                    //'recpaquete_codigorecepcion' => $res->codigoRecepcion,
                    'recpaquete_mensajeslist' => $mensajecadena,
                    'recpaquete_fechahora' => $fecha_hora1,
                    'codigo_evento' => $codigo_evento,
                    'factura_id' => $factura_id,
                );
            }
            $recpaquete_id = $this->Emision_paquetes_model->add_recepcionpaquetes($params);

            /* empieza para la validadcion de recepcion de paquetes */
            $cod_recepcion = $res->codigoRecepcion;
            //var_dump($codigo_recepcion."QQWWQQ");
            sleep(1);
            //if($cod_recepcion != "" && $cod_recepcion != null){
            if($res->codigoDescripcion == "PENDIENTE"){
                $parametros = ["SolicitudServicioValidacionRecepcionPaquete" => [
                    "codigoAmbiente" => $dosificacion['dosificacion_ambiente'],
                    "codigoPuntoVenta"    => $puntoventa['puntoventa_codigo'], //$dosificacion['dosificacion_puntoventa'],
                    "codigoSistema"        => $dosificacion['dosificacion_codsistema'],
                    "codigoSucursal"       => $dosificacion['dosificacion_sucursal'],
                    "nit"              => $dosificacion['dosificacion_nitemisor'],
                    "codigoDocumentoSector"=> $dosificacion['docsec_codigoclasificador'],
                    "codigoEmision"  => $tipo_emision,
                    "codigoModalidad"     => $dosificacion['dosificacion_modalidad'],
                    "cufd"              => $puntoventa['cufd_codigo'], //$dosificacion['dosificacion_cufd'],
                    "cuis"              => $puntoventa['cuis_codigo'], //$dosificacion['dosificacion_cuis'],
                    "tipoFacturaDocumento" => $dosificacion['tipofac_codigo'],
                    "codigoRecepcion"         => $cod_recepcion, //$dosificacion['dosificacion_nitemisor']
                ]];

                $fecha_hora1 = (new DateTime())->format('Y-m-d H:i:s');
                
                $resultado = $cliente->validacionRecepcionPaqueteFactura($parametros);
                $resp = $resultado->RespuestaServicioFacturacion;
                
                if($resp->codigoDescripcion == "VALIDADA"){
                    $params = array(
                        'recpaquete_codigodescripcion' => $resp->codigoDescripcion,
                        'recpaquete_codigoestado' => $resp->codigoEstado,
                    );
                    foreach ($facturas as $f){
                        $sql = "update factura set 
                                 factura_codigodescripcion = 'VALIDADA',
                                factura_enviada = 2,
                                factura_codigorecepcion= '".$resp->codigoRecepcion."'
                                where factura_id = ".$f['factura_id'];
                        $this->Venta_model->ejecutar($sql);
                    }
                    /* da de baja el evento rergistrado cuando todo sale bien!. */
                    $estado_id = 2;
                    $parambe = array(
                        'estado_id' => $estado_id,
                    );
                    $this->Eventos_significativos_model->update_registroevento($evento['registroeventos_id'],$parambe);
                }elseif($resp->codigoDescripcion == "OBSERVADA"){
                    $cad = $resp->mensajesList;
                    $mensajecadena = json_encode($cad);
                    $params = array(
                        'recpaquete_codigodescripcion' => $resp->codigoDescripcion,
                        'recpaquete_codigoestado' => $resp->codigoEstado,
                        'recpaquete_mensajeslist' => $mensajecadena,
                    );
                }
                $this->Emision_paquetes_model->update_recepcionpaquetes($recpaquete_id,$params);
                echo json_encode($resp);
            }else{
                echo json_encode($res);
            }
        }
    }
    
        /* envia correo  a cliente */
    function enviarcorreo($venta_id, $factura_id, $email_destino){
        
        $data['sistema'] = $this->sistema;
        $this->load->library('email');
        $this->email->set_newline("\r\n");
        $this->load->model('Configuracion_email_model');
        $configuracion = $this->Configuracion_email_model->get_configuracion_email(1);

        $config['protocol'] = $configuracion['email_protocolo'];
        $config['smtp_host'] = $configuracion['email_host'];
        $config['smtp_port'] = $configuracion['email_puerto'];
        $config['smtp_user'] = $configuracion['email_usuario'];
        $config['smtp_pass'] = $configuracion['email_clave'];
        $config['smtp_from_name'] = $configuracion['email_nombre'];
        $config['priority'] = $configuracion['email_prioridad'];
        $config['charset'] = $configuracion['email_charset'];
        $config['smtp_crypto'] = $configuracion['email_encriptacion'];
        $config['wordwrap'] = TRUE;
        $config['newline'] = "\r\n";
        $config['mailtype'] = $configuracion['email_tipo'];
        $email_copia = '';

        $this->email->initialize($config);

        $this->email->from($config['smtp_user'], $config['smtp_from_name']);
        $this->email->to($email_destino);
        $this->email->cc($configuracion['email_copia']);
//            $this->email->bcc($attributes['cc']);
        $this->email->subject("Factura Digital, gracias por comprar, vuelva pronto");
        $base_url = explode('/', base_url());
        $nombre_archivo = $this->nombre_archivo;
        $directorio = $_SERVER['DOCUMENT_ROOT'].'/'.$base_url[3].'/resources/xml/';
        $this->email->attach($directorio.$nombre_archivo.$factura_id.".xml");
        $this->email->attach($directorio.$nombre_archivo.$factura_id.".pdf");
        $html = "<html>";
        $html = "<head>";
        $html = "<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css' integrity='sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M' crossorigin='anonymous'>";
        $html = "</head>";
        $html = "<body>";

        $html .= "<div class='container' style='font-family: Arial'>";
        $html .= "<div class='col-md-2' style='background:gray;'></div>";

        $html .= "<div class='col-md-10'>";
        $html .= "<center>";
        $html .= "<h3>Facturacion Electronica</h3>";
        $html .= " ";
        $html .= "<h4>Estimado Usuario</h4>";
        $html .= "<br>";
        //$html .= $configuracion['email_cabecera'];
        $html .= "Le informamos que su factura electrónica se encuentra disponible para verlo en el siguiente enlace: <br>";
        $direccion = base_url("tufactura/verfactura/".md5($venta_id));
        $html .= "<br><a href='".$direccion."' class='btn btn-info btn-sm' > Ver factura electronica</a>";
        $html .= "<br>Tambien le enviamos los archivos en formato PDF y XML adjuntos";
        $html .= "<br>";
        //$html .= "<br><a href='".$direccion."' class='btn btn-info btn-sm' > Activar mi Cuenta</a>";
//            $html .= "<form method='get' action='/".$direccion."'>";
//            $html .= "<button type='submit'>Activar mi Cuenta</button>";
//            $html .= "</form>";

        $html .= "<br>";
        $html .= "<br>";

        //$html .= $configuracion['email_pie'];
        $html .= "<br>";
        $html .= "<br>";
        //$html .= "<br><a href='".$direccion."' class='btn btn-info btn-sm'>".$direccion."</a>";

        $html .= "</center>";
        $html .= "</div>";

        $html .= "<div class='col-md-2'></div>";            
        $html .= "</div>";

        $html .= "</body>";
        $html .= "</html>";


        $this->email->message($html);

        if($this->email->send()) {
            $valor = true;        
        } else {
            $valor = false;
        }
        $this->email->clear(true);
        return $valor;
    }
    
}
