<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Programa_model');
        $this->load->model('Unidad_model');
        $this->load->model('Estado_model');
    } 

    /*
     * Listing of programa
     */
    function index()
    {
        $data['programa'] = $this->Programa_model->get_all_programa();
        $data['estado'] = $this->Estado_model->get_all_estado();
        $data['unidad'] = $this->Unidad_model->get_all_unidad();
        
        $data['_view'] = 'programa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new programa
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'unidad_id' => $this->input->post('unidad_id'),
				'estado_id' => $this->input->post('estado_id'),
				'programa_nombre' => $this->input->post('programa_nombre'),
				'programa_codigo' => $this->input->post('programa_codigo'),
				'programa_descripcion' => $this->input->post('programa_descripcion'),
            );
            
            $programa_id = $this->Programa_model->add_programa($params);
            redirect('programa/index');
        }
        else
        {
			$this->load->model('Unidad_model');
			$data['all_unidad'] = $this->Unidad_model->get_all_unidad();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'programa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a programa
     */
    function edit($programa_id)
    {   
        // check if the programa exists before trying to edit it
        $data['programa'] = $this->Programa_model->get_programa($programa_id);
        
        if(isset($data['programa']['programa_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'unidad_id' => $this->input->post('unidad_id'),
					'estado_id' => $this->input->post('estado_id'),
					'programa_nombre' => $this->input->post('programa_nombre'),
					'programa_codigo' => $this->input->post('programa_codigo'),
					'programa_descripcion' => $this->input->post('programa_descripcion'),
                );

                $this->Programa_model->update_programa($programa_id,$params);            
                redirect('programa/index');
            }
            else
            {
				$this->load->model('Unidad_model');
				$data['all_unidad'] = $this->Unidad_model->get_all_unidad();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'programa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The programa you are trying to edit does not exist.');
    } 
    /*
     * Inactivar programa
     */
    function inactivar($programa_id)
    {
        $programa = $this->Programa_model->get_programa($programa_id);

        // check if the programa exists before trying to delete it
        if(isset($programa['programa_id']))
        {
            $this->Programa_model->inactivar_programa($programa_id);
            redirect('programa/index');
        }
        else
            show_error('The programa you are trying to delete does not exist.');
    }

    /*
     * Deleting programa
     */
    function remove($programa_id)
    {
        $programa = $this->Programa_model->get_programa($programa_id);

        // check if the programa exists before trying to delete it
        if(isset($programa['programa_id']))
        {
            $this->Programa_model->delete_programa($programa_id);
            redirect('programa/index');
        }
        else
            show_error('The programa you are trying to delete does not exist.');
    }
    
}
