<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Responsable_pago extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Responsable_model');
    } 

    /*
     * Listing of responsable
     */
    function index()
    {
        $data['responsable'] = $this->Responsable_model->get_all_responsable();
        
        $data['_view'] = 'responsable_pago/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new responsable
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('responsable_nombre','responsable','trim|required', array('required' => 'Este Campo no debe ser vacio'));
        if($this->form_validation->run())     
        {
            $estado_id = 1;
            $params = array(
				'responsable_nombre' => $this->input->post('responsable_nombre'),
				'estado_id' => $estado_id,
            );
            
            $responsable_id = $this->Responsable_model->add_responsable($params);
            redirect('responsable_pago');
        }
        else
        {            
            $data['_view'] = 'responsable_pago/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a responsable
     */
    function edit($responsable_id)
    {   
        // check if the responsable exists before trying to edit it
        $data['responsable'] = $this->Responsable_model->get_responsable($responsable_id);
        
        if(isset($data['responsable']['responsable_id']))
        {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('responsable_nombre','responsable','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())     
            {   
                $params = array(
                    'responsable_nombre' => $this->input->post('responsable_nombre'),
                    'estado_id' => $this->input->post('estado_id'),
                );

                $this->Responsable_model->update_responsable($responsable_id,$params);            
                redirect('responsable_pago');
            }
            else
            {
                $this->load->model('Estado_model');
                $data['all_estado'] = $this->Estado_model->get_all_estado_tipo1();  
                
                $data['_view'] = 'responsable_pago/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The responsable you are trying to edit does not exist.');
    } 

    /*
     * Deleting responsable
     */
    function remove($responsable_id)
    {
        $responsable = $this->Responsable_model->get_responsable($responsable_id);

        // check if the responsable exists before trying to delete it
        if(isset($responsable['responsable_id']))
        {
            $this->Responsable_model->delete_responsable($responsable_id);
            redirect('responsable_pago/index');
        }
        else
            show_error('The responsable you are trying to delete does not exist.');
    }
    
}
