<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rol extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rol_model');
    } 

    /*
     * Listing of rol
     */
    function index()
    {
        $data['rol'] = $this->Rol_model->get_all_rol();
        
        $data['_view'] = 'rol/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new rol
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('rol_nombre','Rol Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'rol_nombre' => $this->input->post('rol_nombre'),
				'rol_descripcion' => $this->input->post('rol_descripcion'),
            );
            
            $rol_id = $this->Rol_model->add_rol($params);
            redirect('rol/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'rol/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a rol
     */
    function edit($rol_id)
    {   
        // check if the rol exists before trying to edit it
        $data['rol'] = $this->Rol_model->get_rol($rol_id);
        
        if(isset($data['rol']['rol_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('rol_nombre','Rol Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'rol_nombre' => $this->input->post('rol_nombre'),
					'rol_descripcion' => $this->input->post('rol_descripcion'),
                );

                $this->Rol_model->update_rol($rol_id,$params);            
                redirect('rol/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'rol/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rol you are trying to edit does not exist.');
    } 

    /*
     * Deleting rol
     */
    function remove($rol_id)
    {
        $rol = $this->Rol_model->get_rol($rol_id);

        // check if the rol exists before trying to delete it
        if(isset($rol['rol_id']))
        {
            $this->Rol_model->delete_rol($rol_id);
            redirect('rol/index');
        }
        else
            show_error('The rol you are trying to delete does not exist.');
    }
    
}
