<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidad extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Unidad_model');
    } 

    /*
     * Listing of unidad
     */
    function index()
    {
        $data['unidad'] = $this->Unidad_model->get_all_unidad();
        
        $data['_view'] = 'unidad/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new unidad
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'unidad_nombre' => $this->input->post('unidad_nombre'),
				'unidad_codigo' => $this->input->post('unidad_codigo'),
				'unidad_descripcion' => $this->input->post('unidad_descripcion'),
            );
            
            $unidad_id = $this->Unidad_model->add_unidad($params);
            redirect('unidad/index');
        }
        else
        {            
            $data['_view'] = 'unidad/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a unidad
     */
    function edit($unidad_id)
    {   
        // check if the unidad exists before trying to edit it
        $data['unidad'] = $this->Unidad_model->get_unidad($unidad_id);
        
        if(isset($data['unidad']['unidad_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'unidad_nombre' => $this->input->post('unidad_nombre'),
					'unidad_codigo' => $this->input->post('unidad_codigo'),
					'unidad_descripcion' => $this->input->post('unidad_descripcion'),
                );

                $this->Unidad_model->update_unidad($unidad_id,$params);            
                redirect('unidad/index');
            }
            else
            {
                $data['_view'] = 'unidad/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The unidad you are trying to edit does not exist.');
    } 

    /*
     * Deleting unidad
     */
    function remove($unidad_id)
    {
        $unidad = $this->Unidad_model->get_unidad($unidad_id);

        // check if the unidad exists before trying to delete it
        if(isset($unidad['unidad_id']))
        {
            $this->Unidad_model->delete_unidad($unidad_id);
            redirect('unidad/index');
        }
        else
            show_error('The unidad you are trying to delete does not exist.');
    }
    
}
