<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidad_manejo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Unidad_manejo_model');
    } 

    /*
     * Listing of unidad_manejo
     */
    function index()
    {
        $data['unidad_manejo'] = $this->Unidad_manejo_model->get_all_unidad_manejo();
        
        $data['_view'] = 'unidad_manejo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new unidad_manejo
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('umanejo_descripcion','Unidad de Manejo','trim|required', array('required' => 'Este Campo no debe ser vacio'));
        if($this->form_validation->run())     
        {
            $estado_id = 1;
            $params = array(
				'umanejo_descripcion' => $this->input->post('umanejo_descripcion'),
				'estado_id' => $estado_id,
            );
            
            $unidad_manejo_id = $this->Unidad_manejo_model->add_unidad_manejo($params);
            redirect('unidad_manejo');
        }
        else
        {            
            $data['_view'] = 'unidad_manejo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a unidad_manejo
     */
    function edit($umanejo_id)
    {   
        // check if the unidad_manejo exists before trying to edit it
        $data['unidad_manejo'] = $this->Unidad_manejo_model->get_unidad_manejo($umanejo_id);
        
        if(isset($data['unidad_manejo']['umanejo_id']))
        {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('umanejo_descripcion','Unidad de Manejo','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())     
            {   
                $params = array(
                    'umanejo_descripcion' => $this->input->post('umanejo_descripcion'),
                    'estado_id' => $this->input->post('estado_id'),
                );

                $this->Unidad_manejo_model->update_unidad_manejo($umanejo_id,$params);            
                redirect('unidad_manejo/index');
            }
            else
            {
                $this->load->model('Estado_model');
                $data['all_estado'] = $this->Estado_model->get_all_estado_tipo1();  
                
                $data['_view'] = 'unidad_manejo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The unidad_manejo you are trying to edit does not exist.');
    } 

    /*
     * Deleting unidad_manejo
     */
    function remove($umanejo_id)
    {
        $unidad_manejo = $this->Unidad_manejo_model->get_unidad_manejo($umanejo_id);

        // check if the unidad_manejo exists before trying to delete it
        if(isset($unidad_manejo['umanejo_id']))
        {
            $this->Unidad_manejo_model->delete_unidad_manejo($umanejo_id);
            redirect('unidad_manejo/index');
        }
        else
            show_error('The unidad_manejo you are trying to delete does not exist.');
    }
    
}
