<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Articulo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get articulo by articulo_id
     */
    function get_articulo($articulo_id)
    {
        $articulo = $this->db->query("
            SELECT
                *

            FROM
                `articulo`

            WHERE
                `articulo_id` = ?
        ",array($articulo_id))->row_array();

        return $articulo;
    }
        
    /*
     * Get all articulo
     */
    function get_all_articulo()
    {
        $articulo = $this->db->query("
            SELECT
                *

            FROM
                `articulo`

            WHERE
                1 = 1

            ORDER BY `articulo_id` 
        ")->result_array();

        return $articulo;
    }
        
    /*
     * function to add new articulo
     */
    function add_articulo($params)
    {
        $this->db->insert('articulo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update articulo
     */
    function update_articulo($articulo_id,$params)
    {
        $this->db->where('articulo_id',$articulo_id);
        return $this->db->update('articulo',$params);
    }
    
    /*
     * function to delete articulo
     */
    function delete_articulo($articulo_id)
    {
        return $this->db->delete('articulo',array('articulo_id'=>$articulo_id));
    }
}
