<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cambio_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cambio by cambio_id
     */
    function get_cambio($cambio_id)
    {
        $cambio = $this->db->query("
            SELECT
                *

            FROM
                `cambio`

            WHERE
                `cambio_id` = ?
        ",array($cambio_id))->row_array();

        return $cambio;
    }
        
    /*
     * Get all cambio
     */
    function get_all_cambio()
    {
        $cambio = $this->db->query("
            SELECT
                *

            FROM
                `cambio`

            WHERE
                1 = 1

            ORDER BY `cambio_id` DESC
        ")->result_array();

        return $cambio;
    }
        
    /*
     * function to add new cambio
     */
    function add_cambio($params)
    {
        $this->db->insert('cambio',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cambio
     */
    function update_cambio($cambio_id,$params)
    {
        $this->db->where('cambio_id',$cambio_id);
        return $this->db->update('cambio',$params);
    }
    
    /*
     * function to delete cambio
     */
    function delete_cambio($cambio_id)
    {
        return $this->db->delete('cambio',array('cambio_id'=>$cambio_id));
    }
}
