<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoria by categoria_id
     */
    function get_categoria($categoria_id)
    {
        $categoria = $this->db->query("
            SELECT
                *

            FROM
                `categoria`

            WHERE
                `categoria_id` = ?
        ",array($categoria_id))->row_array();

        return $categoria;
    }
        
    /*
     * Get all categoria
     */
    function get_all_categoria()
    {
        $categoria = $this->db->query("
            SELECT
                c.*, e.estado_color, e.estado_descripcion, e.estado_id

            FROM
                categoria c
            LEFT JOIN estado e on c.estado_id = e.estado_id

            ORDER BY c.categoria_id
        ")->result_array();

        return $categoria;
    }
        
    /*
     * function to add new categoria
     */
    function add_categoria($params)
    {
        $this->db->insert('categoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categoria
     */
    function update_categoria($categoria_id,$params)
    {
        $this->db->where('categoria_id',$categoria_id);
        return $this->db->update('categoria',$params);
    }
    
    /*
     * function to delete categoria
     */
    function delete_categoria($categoria_id)
    {
        return $this->db->delete('categoria',array('categoria_id'=>$categoria_id));
    }
    /*
     * function to da de baja una categoria
     */
    function inactivar_categoria($categoria_id)
    {
        $sql = "update categoria set estado_id = 2 where categoria_id = ".$categoria_id;
        
        return $this->db->query($sql);
    }

    function activar_categoria($categoria_id)
    {
        $sql = "update categoria set estado_id = 1 where categoria_id = ".$categoria_id;
        
        return $this->db->query($sql);
    }
    /*
     * Verifica si ya hay una Categoria registrada
     */
    function es_categoria_registrado($categoria_nombre)
    {
        $sql = "SELECT
                      count(c.categoria_id) as resultado
                  FROM
                      categoria c
                 WHERE
                      c.categoria_nombre = '".$categoria_nombre."'";

        $categoria = $this->db->query($sql)->row_array();
        return $categoria['resultado'];
    }
    /*
     * Get all categoria activos
     */
    function get_all_categoria_activo()
    {
        $categoria = $this->db->query("
            SELECT
                c.*, e.estado_color, e.estado_descripcion, e.estado_id

            FROM
                categoria c
            LEFT JOIN estado e on c.estado_id = e.estado_id
            WHERE c.estado_id = 1
            ORDER BY c.categoria_id
        ")->result_array();

        return $categoria;
    }
}
