<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoria by categoria_id
     */
    function get_categoria($categoria_id)
    {
        $categoria = $this->db->query("
            SELECT
                *

            FROM
                `categoria`

            WHERE
                `categoria_id` = ?
        ",array($categoria_id))->row_array();

        return $categoria;
    }
        
    /*
     * Get all categoria
     */
    function get_all_categoria()
    {
        $categoria = $this->db->query("
            SELECT
                c.*, e.estado_color, e.estado_descripcion

            FROM
                categoria c
            LEFT JOIN estado e on c.estado_id = e.estado_id

            ORDER BY c.categoria_id
        ")->result_array();

        return $categoria;
    }
        
    /*
     * function to add new categoria
     */
    function add_categoria($params)
    {
        $this->db->insert('categoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categoria
     */
    function update_categoria($categoria_id,$params)
    {
        $this->db->where('categoria_id',$categoria_id);
        return $this->db->update('categoria',$params);
    }
    
    /*
     * function to delete categoria
     */
    function delete_categoria($categoria_id)
    {
        return $this->db->delete('categoria',array('categoria_id'=>$categoria_id));
    }
}
