<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detalle_pedido by detalleped_id
     */
    function get_detalle_pedido($detalleped_id)
    {
        $detalle_pedido = $this->db->query("
            SELECT
                *

            FROM
                `detalle_pedido`

            WHERE
                `detalleped_id` = ?
        ",array($detalleped_id))->row_array();

        return $detalle_pedido;
    }
        
    /*
     * Get all detalle_pedido
     */
    function get_all_detalle_pedido()
    {
        $detalle_pedido = $this->db->query("
            SELECT
                *

            FROM
                `detalle_pedido`

            WHERE
                1 = 1

            ORDER BY `detalleped_id` 
        ")->result_array();

        return $detalle_pedido;
    }
        
    /*
     * function to add new detalle_pedido
     */
    function add_detalle_pedido($params)
    {
        $this->db->insert('detalle_pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detalle_pedido
     */
    function update_detalle_pedido($detalleped_id,$params)
    {
        $this->db->where('detalleped_id',$detalleped_id);
        return $this->db->update('detalle_pedido',$params);
    }
    
    /*
     * function to delete detalle_pedido
     */
    function delete_detalle_pedido($detalleped_id)
    {
        return $this->db->delete('detalle_pedido',array('detalleped_id'=>$detalleped_id));
    }
}
