<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get estado by estado_id
     */
    function get_estado($estado_id)
    {
        $estado = $this->db->query("
            SELECT
                *

            FROM
                `estado`

            WHERE
                `estado_id` = ?
        ",array($estado_id))->row_array();

        return $estado;
    }
        
    /*
     * Get all estado
     */
    function get_all_estado()
    {
        $estado = $this->db->query("
            SELECT
                *

            FROM
                `estado`

            WHERE
                1 = 1

            ORDER BY `estado_id` 
        ")->result_array();

        return $estado;
    }
        
    /*
     * function to add new estado
     */
    function add_estado($params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//
        
        
        $this->db->insert('estado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estado
     */
    function update_estado($estado_id,$params)
    {

        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        $this->db->where('estado_id',$estado_id);
        return $this->db->update('estado',$params);
    }
    
    /*
     * function to delete estado
     */
    function delete_estado($estado_id)
    {
        //********** registro en bitacora ***********//
        $sql = "estado_id: ".$estado_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        

        return $this->db->delete('estado',array('estado_id'=>$estado_id));
    }
    /*
     * Get all estado
     */
    function get_all_estado_tipo1()
    {
        $estado = $this->db->query("
            SELECT
                e.*

            FROM
                estado e

            WHERE
                e.estado_tipo = 1

            ORDER BY `estado_id` 
        ")->result_array();

        return $estado;
    }

    /*
     * Get estado
     */
    function get_estado_tipo($tipo)
    {
        $estado = $this->db->query("
            SELECT
                e.*

            FROM
                estado e

            WHERE
                e.estado_tipo = ".$tipo."

            ORDER BY `estado_id` 
        ")->result_array();

        return $estado;
    }

            
    function bitacora($sql, $operacion){
        
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."ESTADO'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
    
    
}
