<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gestion_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get gestion by gestion_id
     */
    function get_gestion($gestion_id)
    {
        $gestion = $this->db->query("
            SELECT
                *

            FROM
                `gestion`

            WHERE
                `gestion_id` = ?
        ",array($gestion_id))->row_array();

        return $gestion;
    }
        
    /*
     * Get all gestion
     */
    function get_all_gestion()
    {
        $gestion = $this->db->query("
            SELECT
                g.*, e.estado_color, e.estado_descripcion

            FROM
                gestion g
            LEFT JOIN estado e on g.estado_id = e.estado_id
            ORDER BY g.gestion_id 
        ")->result_array();

        return $gestion;
    }

        
    /*
     * function to add new gestion
     */
    function add_gestion($params)
    {
        //********** registro en bitacora ***********//        
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//
        
        $this->db->insert('gestion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gestion
     */
    function update_gestion($gestion_id,$params)
    {
        //********** registro en bitacora ***********//        
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        $this->db->where('gestion_id',$gestion_id);
        return $this->db->update('gestion',$params);
    }
    
    /*
     * function to delete gestion
     */
    function delete_gestion($gestion_id)
    {
        
        //********** registro en bitacora ***********//        
        $sql = "gestion_id: ".$gestion_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->delete('gestion',array('gestion_id'=>$gestion_id));
    }

    public function get_gestiones()
    {
        $this->db->select('*');
        $this->db->from('gestion');
        $this->db->order_by("gestion_id", "DESC");
        $query = $this->db->get();
        return $query->result();
    }

    public function get_gestion2($gestion_id)
    {
        $this->db->select('*');
        $this->db->from('gestion');
        $this->db->where('gestion_id', $gestion_id);
        //$this->db->limit(1);
        $query = $this->db->get();

        if ($query->num_rows() == 1) {
            return $query->row();
        } else {
            return false;
        }
    }    

    public function ejecutar($sql)
    {
        
        //********** registro en bitacora ***********//        
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        
        $this->db->query($sql);
        return $this->db->insert_id();
        
    }   
    
                
    function bitacora($sql, $operacion){
        
        $sql =  str_replace("'", "`", $sql);
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."GESTION'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
    
}
