<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gestion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gestion by gestion_id
     */
    function get_gestion($gestion_id)
    {
        $gestion = $this->db->query("
            SELECT
                *

            FROM
                `gestion`

            WHERE
                `gestion_id` = ?
        ",array($gestion_id))->row_array();

        return $gestion;
    }
        
    /*
     * Get all gestion
     */
    function get_all_gestion()
    {
        $gestion = $this->db->query("
            SELECT
                g.*, e.estado_color, e.estado_descripcion

            FROM
                gestion g
            LEFT JOIN estado e on g.estado_id = e.estado_id
            ORDER BY g.gestion_id 
        ")->result_array();

        return $gestion;
    }

        
    /*
     * function to add new gestion
     */
    function add_gestion($params)
    {
        $this->db->insert('gestion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gestion
     */
    function update_gestion($gestion_id,$params)
    {
        $this->db->where('gestion_id',$gestion_id);
        return $this->db->update('gestion',$params);
    }
    
    /*
     * function to delete gestion
     */
    function delete_gestion($gestion_id)
    {
        return $this->db->delete('gestion',array('gestion_id'=>$gestion_id));
    }

    public function get_gestiones()
    {
        $this->db->select('*');
        $this->db->from('gestion');
        $this->db->order_by("gestion_id", "DESC");
        $query = $this->db->get();
        return $query->result();
    }

    public function get_gestion2($gestion_id)
    {
        $this->db->select('*');
        $this->db->from('gestion');
        $this->db->where('gestion_id', $gestion_id);
        $this->db->limit(1);
        $query = $this->db->get();

        if ($query->num_rows() == 1) {
            return $query->row();
        } else {
            return false;
        }
    }    
    
}
