<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ingreso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ingreso by ingreso_id
     */
    function get_ingreso($ingreso_id)
    {
        $ingreso = $this->db->query("
            SELECT
                *

            FROM
                `ingreso`

            WHERE
                `ingreso_id` = ?
        ",array($ingreso_id))->row_array();

        return $ingreso;
    }
        
    /*
     * Get all ingreso
     */
    function get_all_ingreso()
    {
        $ingreso = $this->db->query("
            SELECT
                i.*, e.estado_color, e.estado_descripcion, u.unidad_nombre,
                p.pedido_numero, us.usuario_nombre

            FROM
                ingreso i
            LEFT JOIN estado e on i.estado_id = e.estado_id
            LEFT JOIN unidad u on i.unidad_id = u.unidad_id
            LEFT JOIN pedido p on i.pedido_id = p.pedido_id
            LEFT JOIN usuario us on i.usuario_id = us.usuario_id
            
            ORDER BY i.ingreso_id
        ")->result_array();

        return $ingreso;
    }
        
    /*
     * function to add new ingreso
     */
    function add_ingreso($params)
    {
        $this->db->insert('ingreso',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ingreso
     */
    function update_ingreso($ingreso_id,$params)
    {
        $this->db->where('ingreso_id',$ingreso_id);
        return $this->db->update('ingreso',$params);
    }
    
    /*
     * function to delete ingreso
     */
    function delete_ingreso($ingreso_id)
    {
        return $this->db->delete('ingreso',array('ingreso_id'=>$ingreso_id));
    }
}
