<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jerarquia_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get jerarquia by jerarquia_id
     */
    function get_jerarquia($jerarquia_id)
    {
        return $this->db->get_where('jerarquia',array('jerarquia_id'=>$jerarquia_id))->row_array();
    }
        
    /*
     * Get all jerarquia
     */
    function get_all_jerarquia()
    {
        $sql = "SELECT
                j.*, e.estado_color, e.estado_descripcion

            FROM
                jerarquia j

            LEFT JOIN estado e on j.estado_id = e.estado_id
                
            ORDER By j.jerarquia_id DESC";

        $jerarquia = $this->db->query($sql)->result_array();
        return $jerarquia;
    }
        
    /*
     * function to add new jerarquia
     */
    function add_jerarquia($params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//        
        $this->db->insert('jerarquia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jerarquia
     */
    function update_jerarquia($jerarquia_id,$params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//        
        $this->db->where('jerarquia_id',$jerarquia_id);
        return $this->db->update('jerarquia',$params);
    }
    
    /*
     * function to delete jerarquia
     */
    function delete_jerarquia($jerarquia_id)
    {
        
        //********** registro en bitacora ***********//
        $sql = "jerarquia_id: ".$jerarquia_id;
        $this->bitacora($sql,'ELIMINAR');
        //********** fin registro en bitacora ***********//        
        
        return $this->db->delete('jerarquia',array('jerarquia_id'=>$jerarquia_id));
    }
    /*
     * Get all jerarquia tipo 1
     */
    function get_all_jerarquia_activo()
    {
        $sql = "SELECT
                j.*, e.estado_color, e.estado_descripcion

            FROM
                jerarquia j

            LEFT JOIN estado e on j.estado_id = e.estado_id
            WHERE j.estado_id = 1
            ORDER By j.jerarquia_id DESC";

        $jerarquia = $this->db->query($sql)->result_array();
        return $jerarquia;
    }  
                
    function bitacora($sql, $operacion){
        
        $sql =  str_replace("'", "`", $sql);
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."JERARQUIA'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
}
