<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parametros_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

        
    }
    
    /*
     * Get parametro by parametro_id
     */
    function get_parametro($parametro_id)
    {
        $parametro = $this->db->query("
            SELECT
                *
            FROM
                `parametros`
            WHERE
                `parametro_id` = ?
        ",array($parametro_id))->row_array();
        return $parametro;
    }
    
    /*
     * Get articulo by articulo_id
     */
    function get_parametros()
    {
        $sql = "select * from parametros";
        $result = $this->db->query($sql)->row_array();

        return $result;
    }
    
    /*
     * Get articulo by articulo_id
     */
    function get_allparametros()
    {
        $sql = "select * from parametros";
        $result = $this->db->query($sql)->result_array();

        return $result;
    }
    
    /*
     * function to add new parametro
     */
    function add_parametro($params)
    {
        $this->db->insert('parametros',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parametro
     */
    function update_parametro($parametro_id,$params)
    {
        $this->db->where('parametro_id',$parametro_id);
        return $this->db->update('parametros',$params);
    }

     function get_articulox($parametro)
    {
        

        $articulo = $this->db->query("
            SELECT
                a.*

            FROM
                articulo a

            WHERE
                a.articulo_nombre like '%".$parametro."%' or a.articulo_industria like '%".$parametro."%'
                  or a.articulo_codigo like '%".$parametro."%'

        ")->result_array();

        return $articulo;
    }
        
    /*
     * Get all articulo
     */
    function get_all_articulo()
    {
        $articulo = $this->db->query("
            SELECT
                a.*, e.estado_color, e.estado_descripcion, e.estado_id, c.categoria_nombre

            FROM
                articulo a
                LEFT JOIN estado e on a.estado_id = e.estado_id
                LEFT JOIN categoria c on a.categoria_id = c.categoria_id
            WHERE
                a.estado_id = e.estado_id

            ORDER BY a.articulo_id
        ")->result_array();

        return $articulo;
    }
        
    /*
     * function to add new articulo
     */
    function add_articulo($params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//
        
        $this->db->insert('articulo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update articulo
     */
    function update_articulo($articulo_id,$params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        $this->db->where('articulo_id',$articulo_id);
        return $this->db->update('articulo',$params);
    }
    
    /*
     * function to delete articulo
     */
    function delete_articulo($articulo_id)
    {
        
        //********** registro en bitacora ***********//
        $sql =" articulo_id:".$articulo_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        
        
        
        return $this->db->delete('articulo',array('articulo_id'=>$articulo_id));
    }
    /*
     * function to da de baja una articulo
     */
    function inactivar_articulo($articulo_id)
    {
        $sql = "update articulo set estado_id = 2 where articulo_id = ".$articulo_id;
        
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->query($sql);
    }
    function activar_articulo($articulo_id)
    {
        $sql = "update articulo set estado_id = 1 where articulo_id = ".$articulo_id;
        
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->query($sql);
    }
      
    function bitacora($sql, $operacion){
        
        $sql =  str_replace("'", "`", $sql);
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."ARTICULO'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
}
