<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pedido by pedido_id
     */
    function get_pedido($pedido_id)
    {
        $pedido = $this->db->query("
            SELECT
                *

            FROM
                `pedido`

            WHERE
                `pedido_id` = ?
        ",array($pedido_id))->row_array();

        return $pedido;
    }
        
    /*
     * Get all pedido
     */
    function get_all_pedido()
    {
        $pedido = $this->db->query("
            SELECT
                *

            FROM
                `pedido`

            WHERE
                1 = 1

            ORDER BY `pedido_id` DESC
        ")->result_array();

        return $pedido;
    }
        
    /*
     * function to add new pedido
     */
    function add_pedido($params)
    {
        $this->db->insert('pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedido
     */
    function update_pedido($pedido_id,$params)
    {
        $this->db->where('pedido_id',$pedido_id);
        return $this->db->update('pedido',$params);
    }
    
    /*
     * function to delete pedido
     */
    function delete_pedido($pedido_id)
    {
        return $this->db->delete('pedido',array('pedido_id'=>$pedido_id));
    }
}
