<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pedido by pedido_id
     */
    function get_pedido($pedido_id)
    {
        $pedido = $this->db->query("
            SELECT
                *

            FROM
                `pedido`

            WHERE
                `pedido_id` = ?
        ",array($pedido_id))->row_array();

        return $pedido;
    }
        
    /*
     * Get all pedido
     */
    function get_all_pedido()
    {
        $pedido = $this->db->query("
            SELECT
                p.*, e.estado_color, e.estado_descripcion, g.gestion_nombre, u.unidad_nombre,t.programa_nombre 

            FROM
                pedido p

            LEFT JOIN estado e on p.estado_id = e.estado_id
            LEFT JOIN gestion g on p.gestion_id = g.gestion_id
            LEFT JOIN unidad u on p.unidad_id = u.unidad_id
            LEFT JOIN programa t on p.programa_id = t.programa_id
            
            WHERE p.estado_id = 6
            ORDER BY p.pedido_id DESC 
            
        ")->result_array();

        return $pedido;
    }
        
    /*
     * function to add new pedido
     */
    function add_pedido($params)
    {
        $this->db->insert('pedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedido
     */
    function update_pedido($pedido_id,$params)
    {
        $this->db->where('pedido_id',$pedido_id);
        return $this->db->update('pedido',$params);
    }
    
    /*
     * function to delete pedido
     */
    function delete_pedido($pedido_id)
    {
        return $this->db->delete('pedido',array('pedido_id'=>$pedido_id));
    }
    /*
     * Get all articulo parametro
     */
    function get_all_pedidoparametro($parametro, $categoria)
    {
        $pedido = $this->db->query("
            SELECT
                p.*, e.estado_color, e.estado_descripcion, e.estado_id,
                u.unidad_nombre, pr.programa_nombre, g.gestion_nombre

            FROM
                pedido p
                LEFT JOIN estado e on p.estado_id = e.estado_id
                LEFT JOIN unidad u on p.unidad_id = u.unidad_id
                LEFT JOIN programa pr on p.programa_id = pr.programa_id
                LEFT JOIN gestion g on p.gestion_id = g.gestion_id
            
            WHERE
                p.estado_id = e.estado_id
                and (p.pedido_numero like '%".$parametro."%')
                ".$categoria."
            GROUP BY
                p.pedido_id

            ORDER BY p.pedido_id
        ")->result_array();

        return $pedido;
    }
    
    /*
     * cantidad de pedidos
     */
    function get_pedido_count()
    {
        $sql = "select if(count(*)>0,count(*),0) as cantidad_pedido from pedido where estado_id = 6";
        return $this->db->query($sql)->result_array();
    }
    
    /*
     * cantidad de pedidos
     */
    function get_pedidos()
    {
        $sql = "select if(count(*)>0,count(*),0) as cantidad_pedido from pedido where estado_id = 6";
        return $this->db->query($sql)->result_array();
    }
    /*
     * Get all unidad parametro
     */
    function get_unidadparametro($parametro)
    {
        $unidad = $this->db->query("
            SELECT
                u.unidad_id, u.unidad_nombre
            FROM
                unidad u
                LEFT JOIN estado e on u.estado_id = e.estado_id
            WHERE
                u.estado_id = e.estado_id
                and u.estado_id = 1
                and (u.unidad_nombre like '%".$parametro."%')
            ORDER BY u.unidad_nombre
        ")->result_array();

        return $unidad;
    }
    /*
     * Get all programa parametro
     */
    function get_programaparametro($parametro)
    {
        $programa = $this->db->query("
            SELECT
                p.programa_id, p.programa_nombre
            FROM
                programa p
                LEFT JOIN estado e on p.estado_id = e.estado_id
            WHERE
                p.estado_id = e.estado_id
                and p.estado_id = 1
                and (p.programa_nombre like '%".$parametro."%')
            ORDER BY p.programa_nombre
        ")->result_array();

        return $programa;
    }
    
    /*
     * Get pedido join unidad y programa by pedido_id
     */
    function get_pedidojoin($pedido_id)
    {
        $pedido = $this->db->query("
            SELECT
                p.*, u.unidad_nombre, pr.programa_nombre

            FROM
                pedido p
                LEFT JOIN unidad u on p.unidad_id = u.unidad_id
                LEFT JOIN programa pr on p.programa_id = pr.programa_id
            WHERE
                p.pedido_id = ?
        ",array($pedido_id))->row_array();

        return $pedido;
    }
    /* Buscar pedidos para exportar a exel */
    function get_all_pedidoexcel($parametro, $categoria)
    {
        $pedido = $this->db->query("
            SELECT
                p.pedido_numero as PEDIDO, u.unidad_nombre as UNIDAD,
                pr.programa_nombre as PROGRAMA, p.pedido_fechapedido as FECHA,
                concat(p.pedido_fecha,' ', p.pedido_hora) as FECHA_REGISTRO, g.gestion_nombre as GESTION,
                e.estado_descripcion as ESTADO
                
            FROM
                pedido p
                LEFT JOIN estado e on p.estado_id = e.estado_id
                LEFT JOIN unidad u on p.unidad_id = u.unidad_id
                LEFT JOIN programa pr on p.programa_id = pr.programa_id
                LEFT JOIN gestion g on p.gestion_id = g.gestion_id
            
            WHERE
                p.estado_id = e.estado_id
                and (p.pedido_numero like '%".$parametro."%')
                ".$categoria."
            GROUP BY
                p.pedido_id

            ORDER BY p.pedido_id
        ")->result_array();

        return $pedido;
    }
    /*
     * Funcion que verifica si un pedido fue usado en otros modulos
     */
    function pedido_es_usado($pedido_id){
        $producto = $this->db->query("
            SELECT COUNT(p.pedido_id) AS res
             FROM pedido p
             WHERE
                  p.estado_id <> 6
                  and p.pedido_id = $pedido_id
        ")->row_array();
/*SELECT sum(
            (SELECT if(count(dp.pedido_id) > 0, count(dp.pedido_id), 0) AS FIELD_1
             FROM detalle_pedido dp
             WHERE dp.pedido_id = p.pedido_id and dp.pedido_id = $pedido_id) +
            (SELECT if(count(pe.pedido_id) > 0, count(pe.pedido_id), 0) AS FIELD_1
             FROM pedido pe
             WHERE pe.pedido_id = p.pedido_id and p.pedido_id = $pedido_id)) as res
             FROM
                pedido p
              WHERE p.pedido_id = $pedido_id*/
        return $producto['res'];
    }
}
