<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get programa by programa_id
     */
    function get_programa($programa_id)
    {
        $programa = $this->db->query("
            SELECT
                *

            FROM
                `programa`

            WHERE
                `programa_id` = ?
        ",array($programa_id))->row_array();

        return $programa;
    }
        
    /*
     * Get all programa
     */
    function get_all_programa()
    {
        $programa = $this->db->query("
            SELECT
                *

            FROM
                `programa`

            WHERE
                1 = 1

            ORDER BY `programa_id` DESC
        ")->result_array();

        return $programa;
    }
        
    /*
     * function to add new programa
     */
    function add_programa($params)
    {
        $this->db->insert('programa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update programa
     */
    function update_programa($programa_id,$params)
    {
        $this->db->where('programa_id',$programa_id);
        return $this->db->update('programa',$params);
    }
    
    /*
     * function to delete programa
     */
    function delete_programa($programa_id)
    {
        return $this->db->delete('programa',array('programa_id'=>$programa_id));
    }
}
