<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Proveedor_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
                
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get proveedor by proveedor_id
     */
    function get_proveedor($proveedor_id)
    {
        $proveedor = $this->db->query("
            SELECT
                *

            FROM
                `proveedor`

            WHERE
                `proveedor_id` = ?
        ",array($proveedor_id))->row_array();

        return $proveedor;
    }
        
    /*
     * Get all proveedor
     */
    function get_all_proveedor($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $proveedor = $this->db->query("
            SELECT
                p.*, e.*

            FROM
                proveedor p, estado e

            WHERE
                p.estado_id=e.estado_id

            ORDER BY `proveedor_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $proveedor;
    }
        
    /*
     * function to add new proveedor
     */
    function add_proveedor($params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERTAR');
        //********** fin registro en bitacora ***********//        
        
        
        $this->db->insert('proveedor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update proveedor
     */
    function update_proveedor($proveedor_id,$params)
    {
        
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//        
        $this->db->where('proveedor_id',$proveedor_id);
        return $this->db->update('proveedor',$params);
    }
    
    /*
     * function to delete proveedor
     */
    function delete_proveedor($proveedor_id)
    {
        //********** registro en bitacora ***********//
        $sql = "proveedor_id: ".$proveedor_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//        
        return $this->db->delete('proveedor',array('proveedor_id'=>$proveedor_id));
    }
    
    /*
     * Muestra la cantida de proveedores activos
     */
    function get_proveedor_count()
    {
        $sql = "select if(count(*)>0,count(*),0) as cantidad_proveedor from proveedor";
        return $this->db->query($sql)->result_array();
        
    }

    function inactivar_proveedor($proveedor_id)
    {
        $sql = "update proveedor set estado_id = 2 where proveedor_id = ".$proveedor_id;
        
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//        
        
        return $this->db->query($sql);
    }
    function activar_proveedor($proveedor_id)
    {
        $sql = "update proveedor set estado_id = 1 where proveedor_id = ".$proveedor_id;
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//        
        

        
        return $this->db->query($sql);
    }
            
    function bitacora($sql, $operacion){
        
        $sql =  str_replace("'", "`", $sql);
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."PROVEEDOR'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }    
}
