<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
   
class Rol_usuario_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get rol_usuario by id_rol_usuario
     */
    function get_rol_usuario($id_rol_usuario)
    {
        return $this->db->get_where('rol_usuario',array('id_rol_usuario'=>$id_rol_usuario))->row_array();
        /*return $this->db->get_where('rol_usuario',array('rol_id'=>$rol_id))->row_array();
        return $this->db->get_where('rol_usuario',array('tipousuario_id'=>$tipousuario_id))->row_array();*/
    }
    
    /*
     * Get all rol_usuario count
     */
    function get_all_rol_usuario_count()
    {
        $this->db->from('rol_usuario');
        return $this->db->count_all_results();
    }
      
    /*
     * function to add new rol_usuario
     */
    function add_rol_usuario($params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//
            
        // $rol_id = array('rol_id' =>$rol_id );
       $rol_id=1;
        $this->db->insert('rol_usuario',$params);
        return $this->db->insert_id('tipousuario_id', $rol_id = array('rol_id' =>$rol_id ));
    }
    
    /*
     * function to update rol_usuario
     */
    function update_rol_usuario($id_rol_usuario,$params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        $this->db->where('id_rol_usuario',$id_rol_usuario);
        return $this->db->update('rol_usuario',$params);
    }
    
    /*
     * function to delete rol_usuario
     */
    function delete_rol_usuario($id_rol_usuario)
    {
        //********** registro en bitacora ***********//
        $sql = "$id_rol_usuario : ".$id_rol_usuario;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->delete('rol_usuario',array('id_rol_usuario'=>$id_rol_usuario));
    }
    
    /*
     * Get all rol_usuario from tipo_usuario
     */
    function getall_rolusuario($tipousuario_id)
    {
        $rol_usuario = $this->db->query("
            SELECT
                ru.rol_id, ru.rolusuario_asignado
            FROM
                rol_usuario ru
            WHERE
                ru.tipousuario_id = $tipousuario_id
            order by ru.rol_id
        ")->result_array();
        return $rol_usuario;
    }
    function get_allrol_tipousuario($tipousuario_id)
    {
        $rol = $this->db->query("
            SELECT
                ru.*, r.rol_nombre, r.rol_descripcion
            FROM
                rol_usuario ru, rol r
            WHERE
                ru.rol_id = r.rol_id
                and ru.tipousuario_id = $tipousuario_id
        ")->result_array();
        return $rol;
    }
    function get_allrol_tipousuariopadre($tipousuario_id)
    {
        $rol = $this->db->query("
            SELECT
                ru.*, r.rol_nombre, r.rol_descripcion
            FROM
                rol_usuario ru, rol r
            WHERE
                ru.rol_id = r.rol_id
                and r.rol_idfk = 0
                and ru.tipousuario_id = $tipousuario_id
        ")->result_array();
        return $rol;
    }
    function get_allrol_tipousuariohijo($tipousuario_id)
    {
        $rol = $this->db->query("
            SELECT
                ru.*, r.rol_nombre, r.rol_descripcion, r.rol_idfk
            FROM
                rol_usuario ru, rol r
            WHERE
                ru.rol_id = r.rol_id
                and r.rol_idfk != 0
                and ru.tipousuario_id = $tipousuario_id
        ")->result_array();
        return $rol;
    }
    /*
     * function to delete all rol_usuario de un tipo de usuario
     */
    function delete_rolusuario_fromtipous($tipousuario_id)
    {
        
        //********** registro en bitacora ***********//
        $sql = "tipousuario_id : ".$tipousuario_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
                
        return $this->db->delete('rol_usuario',array('tipousuario_id'=>$tipousuario_id));
    }
          
    function bitacora($sql, $operacion){
        
        $sql =  str_replace("'", "`", $sql);
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."ROL USUARIO'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
    
}
