<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Salida_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get salida by salida_id
     */
    function get_salida($salida_id)
    {
        $salida = $this->db->query("
            SELECT
                *

            FROM
                `salida`

            WHERE
                `salida_id` = ?
        ",array($salida_id))->row_array();

        return $salida;
    }
        
    /*
     * Get all salida
     */
    function get_all_salida()
    {
        $salida = $this->db->query("
            SELECT
                *

            FROM
                `salida`

            WHERE
                1 = 1

            ORDER BY `salida_id` 
        ")->result_array();

        return $salida;
    }
        
    /*
     * function to add new salida
     */
    function add_salida($params)
    {
        $this->db->insert('salida',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update salida
     */
    function update_salida($salida_id,$params)
    {
        $this->db->where('salida_id',$salida_id);
        return $this->db->update('salida',$params);
    }
    
    /*
     * function to delete salida
     */
    function delete_salida($salida_id)
    {
        return $this->db->delete('salida',array('salida_id'=>$salida_id));
    }
}
