<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_usuario_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get tipo_usuario by tipousuario_id
     */
    function get_tipo_usuario($tipousuario_id)
    {
        $tipo_usuario = $this->db->query("
            SELECT
                *

            FROM
                `tipo_usuario`

            WHERE
                `tipousuario_id` = ?
        ",array($tipousuario_id))->row_array();

        return $tipo_usuario;
    }
        
    /*
     * Get all tipo_usuario
     */
    function get_all_tipo_usuario()
    {
        $tipo_usuario = $this->db->query("
            SELECT
                *

            FROM
                `tipo_usuario`

            WHERE
                1 = 1

            ORDER BY `tipousuario_id` 
        ")->result_array();

        return $tipo_usuario;
    }
        
    /*
     * function to add new tipo_usuario
     */
    function add_tipo_usuario($params)
    {
        
        //********** registro en bitacora ***********// 
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//
        
        
        $this->db->insert('tipo_usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_usuario
     */
    function update_tipo_usuario($tipousuario_id,$params)
    {
        
        //********** registro en bitacora ***********// 
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        $this->db->where('tipousuario_id',$tipousuario_id);
        return $this->db->update('tipo_usuario',$params);
    }
    
    /*
     * function to delete tipo_usuario
     */
    function delete_tipo_usuario($tipousuario_id)
    {
        //********** registro en bitacora ***********// 
        $sql = "tipousuario_id : ".$tipousuario_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->delete('tipo_usuario',array('tipousuario_id'=>$tipousuario_id));
    }

    function inactivar_tipo_usuario($tipousuario_id)
    {
        $sql = "update tipo_usuario set estado_id = 2 where tipousuario_id = ".$tipousuario_id;
        //********** registro en bitacora ***********// 
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//        
        
        return $this->db->query($sql);
    }
    /*
     * Get nombre detipo_usuario by tipousuario_id
     */
    function get_tipousuario_nombre($tipousuario_id)
    {
        $tipo_usuario = $this->db->query("
            SELECT
                t.tipousuario_descripcion

            FROM
                tipo_usuario t

            WHERE
                t.tipousuario_id = ?
        ",array($tipousuario_id))->row_array();

        return $tipo_usuario['tipousuario_descripcion'];
    }
            
    function bitacora($sql, $operacion){
        
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."TIPO_USUARIO'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }    
    
}
