<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidad_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get unidad by unidad_id
     */
    function get_unidad($unidad_id)
    {
        $unidad = $this->db->query("
            SELECT
                *

            FROM
                `unidad`

            WHERE
                `unidad_id` = ?
        ",array($unidad_id))->row_array();

        return $unidad;
    }
        
    /*
     * Get all unidad
     */
    function get_all_unidad()
    {
        $unidad = $this->db->query("
            SELECT
                *

            FROM
                `unidad`

            WHERE
                1 = 1

            ORDER BY `unidad_nombre` 
        ")->result_array();

        return $unidad;
    }
    function get_todo_unidad()
    {
        $unidad = $this->db->query("
            SELECT
                u.*, e.estado_color, e.estado_descripcion, j.jerarquia_nombre

            FROM
                unidad u
            LEFT JOIN estado e on u.estado_id = e.estado_id
            LEFT JOIN jerarquia j on u.jerarquia_id = j.jerarquia_id

            WHERE
                u.estado_id=e.estado_id

            ORDER BY u.unidad_id
        ")->result_array();

        return $unidad;
    }  
    /*
     * function to add new unidad
     */
    function add_unidad($params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//
        
        $this->db->insert('unidad',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidad
     */
    function update_unidad($unidad_id,$params)
    {
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        $this->db->where('unidad_id',$unidad_id);
        return $this->db->update('unidad',$params);
    }
    
    /*
     * function to delete unidad
     */
    function delete_unidad($unidad_id)
    {
        //********** registro en bitacora ***********//
        $sql = "unidad_id: ".$unidad_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->delete('unidad',array('unidad_id'=>$unidad_id));
    }

    function inactivar_unidad($unidad_id)
    {
        
        $sql = "update unidad set estado_id = 2 where unidad_id = ".$unidad_id;
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->query($sql);
    }
    
    function activar_unidad($unidad_id)
    {
        $sql = "update unidad set estado_id = 1 where unidad_id = ".$unidad_id;
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        
        return $this->db->query($sql);
    }
    
    function get_unidad_count()
    {
        $sql = "select if(count(*)>0,count(*),0) as cantidad_unidad from unidad where estado_id = 1";
        $unidad = $this->db->query($sql)->result_array();

        return $unidad;
    }    
    
        
            
    function bitacora($sql, $operacion){
        
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."UNIDAD'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
    
}
