<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unidad by unidad_id
     */
    function get_unidad($unidad_id)
    {
        $unidad = $this->db->query("
            SELECT
                *

            FROM
                `unidad`

            WHERE
                `unidad_id` = ?
        ",array($unidad_id))->row_array();

        return $unidad;
    }
        
    /*
     * Get all unidad
     */
    function get_all_unidad()
    {
        $unidad = $this->db->query("
            SELECT
                *

            FROM
                `unidad`

            WHERE
                1 = 1

            ORDER BY `unidad_nombre` 
        ")->result_array();

        return $unidad;
    }
    function get_todo_unidad()
    {
        $unidad = $this->db->query("
            SELECT
                u.*, e.*

            FROM
                unidad u, estado e

            WHERE
                u.estado_id=e.estado_id

            ORDER BY `unidad_id` 
        ")->result_array();

        return $unidad;
    }  
    /*
     * function to add new unidad
     */
    function add_unidad($params)
    {
        $this->db->insert('unidad',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidad
     */
    function update_unidad($unidad_id,$params)
    {
        $this->db->where('unidad_id',$unidad_id);
        return $this->db->update('unidad',$params);
    }
    
    /*
     * function to delete unidad
     */
    function delete_unidad($unidad_id)
    {
        return $this->db->delete('unidad',array('unidad_id'=>$unidad_id));
    }

    function inactivar_unidad($unidad_id)
    {
        $sql = "update unidad set estado_id = 2 where unidad_id = ".$unidad_id;
        
        return $this->db->query($sql);
    }
    
    function get_unidad_count()
    {
        $sql = "select if(count(*)>0,count(*),0) as cantidad_unidad from unidad where estado_id = 1";
        $unidad = $this->db->query($sql)->result_array();

        return $unidad;
    }    
}
