<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidad_manejo_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get unidad_manejo by umanejo_id
     */
    function get_unidad_manejo($umanejo_id)
    {
        return $this->db->get_where('unidad_manejo',array('umanejo_id'=>$umanejo_id))->row_array();
    }
        
    /*
     * Get all unidad_manejo
     */
    function get_all_unidad_manejo()
    {
        $sql = "SELECT
                um.*, e.estado_color, e.estado_descripcion

            FROM
                unidad_manejo um

            LEFT JOIN estado e on um.estado_id = e.estado_id
                
            ORDER By um.umanejo_id DESC";

        $umanejo = $this->db->query($sql)->result_array();
        return $umanejo;
    }
        
    /*
     * function to add new unidad_manejo
     */
    function add_unidad_manejo($params)
    {
                
        //********** registro en bitacora ***********// 
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//

        
        $this->db->insert('unidad_manejo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidad_manejo
     */
    function update_unidad_manejo($umanejo_id,$params)
    {
                
        //********** registro en bitacora ***********// 
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//

        $this->db->where('umanejo_id',$umanejo_id);
        return $this->db->update('unidad_manejo',$params);
    }
    
    /*
     * function to delete unidad_manejo
     */
    function delete_unidad_manejo($umanejo_id)
    {
                
        //********** registro en bitacora ***********// 
        $sql = "umanejo_id: ".$umanejo_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        return $this->db->delete('unidad_manejo',array('umanejo_id'=>$umanejo_id));
    }
    /*
     * Get all unidad_manejo tipo 1
     */
    function get_all_unidad_manejo_activo()
    {
        $sql = "SELECT
                um.*, e.estado_color, e.estado_descripcion

            FROM
                unidad_manejo um

            LEFT JOIN estado e on um.estado_id = e.estado_id
            WHERE um.estado_id = 1
            ORDER By um.umanejo_id DESC";

        $umanejo = $this->db->query($sql)->result_array();
        return $umanejo;
    }

    function inactivar_unidad($umanejo_id)
    {
        $sql = "update unidad_manejo set estado_id = 2 where umanejo_id = ".$umanejo_id;
                
        //********** registro en bitacora ***********// 
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->query($sql);
    }
    function activar_unidad($umanejo_id)
    {
        $sql = "update unidad_manejo set estado_id = 1 where umanejo_id = ".$umanejo_id;
        //********** registro en bitacora ***********// 
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//
        
        return $this->db->query($sql);
    }
                
    function bitacora($sql, $operacion){
        
        $sql =  str_replace("'", "`", $sql);
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."UNIDAD MANEJO'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
}

