<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        
        $this->session_data = $this->session->userdata('logged_in');

    }
    
    /*
     * Get usuario by usuario_id
     */
    function get_usuario($usuario_id)
    {
        $usuario = $this->db->query("
            SELECT
                *

            FROM
                `usuario`

            WHERE
                `usuario_id` = ?
        ",array($usuario_id))->row_array();

        return $usuario;
    }
        
    /*
     * Get all usuario
     */
    function get_all_usuario()
    {
        $usuario = $this->db->query("
            SELECT
                *

            FROM
                `usuario`

            WHERE
                1 = 1

            ORDER BY `usuario_id` 
        ")->result_array();

        return $usuario;
    }

    function get_todos_usuario()
    {
        $usuario = $this->db->query("
            SELECT
                u.*, e.*, tu.*

            FROM
                usuario u, estado e, tipo_usuario tu

            WHERE
                u.estado_id=e.estado_id
                and u.tipousuario_id=tu.tipousuario_id

            ORDER BY `usuario_id` 
        ")->result_array();

        return $usuario;
    }
     public function getCurrentPassword($usuario_id)
    {

        //********** registro en bitacora ***********//
        $sql = "solicitus contraseña, usuario_id: ".$usuario_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
         
        $query = $this->db->where('usuario_id',$usuario_id)
                        ->get('usuario');
            if ($query->num_rows() > 0) {
                return $query->row();
            }
    }
    
    public function password($usuario_id, $new_password)
    {
            
        //********** registro en bitacora ***********//
        $sql = "usuario_id: ".usuario_id.", contraseña: ".$new_password;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//
        
            $data = array(
                    'usuario_clave'=> $new_password
            );
            $this->db->where('usuario_id',$usuario_id);
             return $this->db->update('usuario',$data);
    }
        
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        
        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'INSERT');
        //********** fin registro en bitacora ***********//
        
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($usuario_id,$params)
    {

        //********** registro en bitacora ***********//
        $sql = json_encode($params);
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//        
        
        $this->db->where('usuario_id',$usuario_id);
        return $this->db->update('usuario',$params);
        
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($usuario_id)
    {
        
        //********** registro en bitacora ***********//
        $sql = "usuario_id: ".$usuario_id;
        $this->bitacora($sql,'DELETE');
        //********** fin registro en bitacora ***********//        
        
        return $this->db->delete('usuario',array('usuario_id'=>$usuario_id));
    }

    function inactivar_usuario($usuario_id)
    {
        $sql = "update usuario set estado_id = 2 where usuario_id = ".$usuario_id;
        
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//        
        
        return $this->db->query($sql);
    }
    function activar_usuario($usuario_id)
    {
        $sql = "update usuario set estado_id = 1 where usuario_id = ".$usuario_id;
        
        //********** registro en bitacora ***********//
        $this->bitacora($sql,'UPDATE');
        //********** fin registro en bitacora ***********//        
                
        return $this->db->query($sql);
    }
    
    function get_all_usuario_activo()
    {
        $usuario = $this->db->query("
            SELECT
                u.*

            FROM
                usuario u

            WHERE
                u.estado_id = 1

            ORDER BY u.usuario_nombre
        ")->result_array();

        return $usuario;
    }
    
            
    function bitacora($sql, $operacion){
        
        $usuario_id = $this->session_data['usuario_id'];
        
        $bitacora_fecha = "'".date("Y-m-d")."'";
        $bitacora_hora = "'".date("H:i:s")."'";
        $bitacora_operacion = "'".$operacion." "."USUARIO'";
        $bitacora_consulta = "'".$sql."'";
        $bitacora_anterior ="''";
        
        $sql = "insert into bitacora(bitacora_fecha,bitacora_hora,bitacora_operacion,bitacora_consulta,bitacora_anterior,usuario_id) value(".
                $bitacora_fecha.",".$bitacora_hora.",".$bitacora_operacion.",".$bitacora_consulta.",".$bitacora_anterior.",".$usuario_id.")";
    
        $this->db->query($sql);
        return true;
    }
    
}
